package io.github.erkko68.filament

/**
 * IndirectLight is used to simulate environment lighting, a form of global illumination.
 *
 * Environment lighting provides two components:
 * - **Irradiance:** Diffuse lighting from the environment (brightness in all directions)
 * - **Reflections:** Specular component (environment map reflections on shiny surfaces)
 *
 * Environments are typically captured as high-resolution HDR equirectangular images and
 * processed by the **cmgen** tool to generate the data for IndirectLight.
 *
 * **Usage:**
 * Only one IndirectLight can be active in a Scene at a time. Create it with the Builder
 * and assign it to the scene via [Scene.setIndirectLight]. Destroy with [Engine.destroy].
 *
 * **Spherical harmonics:**
 * Irradiance and radiance can be specified as spherical harmonics (SH) coefficients for
 * memory efficiency. Use 1, 2, or 3 bands for 1, 4, or 9 coefficients respectively.
 * The **cmgen** tool generates properly scaled SH coefficients.
 */
expect class IndirectLight {
    /**
     * Builder for creating IndirectLight instances.
     *
     * Set reflections and/or irradiance, configure intensity and rotation, then call build().
     */
    class Builder() {
        /**
         * Sets the reflections cubemap mipmap chain.
         *
         * The cubemap must be generated by the **cmgen** tool. Each mipmap level encodes
         * the irradiance for a different roughness level.
         *
         * @param cubemap Mip-mapped cubemap (or null to clear)
         * @return This Builder, for chaining calls
         */
        fun reflections(cubemap: Texture): Builder

        /**
         * Sets the irradiance from pre-convolved spherical harmonics coefficients.
         *
         * Coefficients must already be pre-scaled by the reconstruction factors and
         * the Lambertian diffuse BRDF (1/π). Generate with the **cmgen** tool.
         *
         * @param bands Number of SH bands (1, 2, or 3)
         * @param sh Array of 3D coefficients; size = bands² (1, 4, or 9 float3 values)
         * @return This Builder, for chaining calls
         *
         * @see Material.Builder.sphericalHarmonicsBandCount
         */
        fun irradiance(bands: Int, sh: FloatArray): Builder

        /**
         * Sets the irradiance computed from radiance spherical harmonics coefficients.
         *
         * Coefficients are raw radiance values (not pre-convolved). The builder
         * automatically convolves them and applies the Lambertian BRDF.
         *
         * @param bands Number of SH bands (1, 2, or 3)
         * @param sh Array of 3D coefficients; size = bands² (1, 4, or 9 float3 values)
         * @return This Builder, for chaining calls
         */
        fun radiance(bands: Int, sh: FloatArray): Builder

        /**
         * Sets the irradiance cubemap (for diffuse lighting only).
         *
         * If not provided, irradiance is computed automatically from the reflections cubemap.
         *
         * @param cubemap Cubemap texture for irradiance (or null to clear)
         * @return This Builder, for chaining calls
         */
        fun irradiance(cubemap: Texture): Builder

        /**
         * Sets the environment's overall intensity multiplier.
         *
         * This scales the contribution of both irradiance and reflections.
         * Default: 1.0.
         *
         * @param envIntensity Intensity multiplier (e.g., 0.5 to dim, 2.0 to brighten)
         * @return This Builder, for chaining calls
         */
        fun intensity(envIntensity: Float): Builder

        /**
         * Rotates the environment mapping.
         *
         * Allows repositioning of the environment without re-processing the cubemaps.
         *
         * @param rotation 3x3 rotation matrix as a 9-element array (or identity if not set)
         * @return This Builder, for chaining calls
         */
        fun rotation(rotation: FloatArray): Builder

        /**
         * Creates the IndirectLight object.
         *
         * @param engine Engine to associate this IndirectLight with
         * @return The newly created IndirectLight
         */
        fun build(engine: Engine): IndirectLight
    }

    /**
     * Gets/sets the environment's overall intensity multiplier.
     *
     * Scales the contribution of both irradiance and reflections. Default: 1.0.
     */
    var intensity: Float

    /**
     * Gets/sets the environment rotation as a 3x3 matrix.
     *
     * Allows dynamic repositioning without re-processing cubemaps.
     */
    var rotation: FloatArray

    /**
     * Gets the reflections cubemap texture (if set).
     * @return The reflections cubemap, or null if not provided
     */
    val reflectionsTexture: Texture?

    /**
     * Gets the irradiance cubemap texture (if set).
     * @return The irradiance cubemap, or null if computed from reflections
     */
    val irradianceTexture: Texture?

    companion object {
        /**
         * Estimates the dominant direction of light from spherical harmonics coefficients.
         *
         * Useful for determining the main light direction for analysis or debugging.
         *
         * @param sh Spherical harmonics coefficients array
         * @param out Optional FloatArray for result; created if null
         * @return The dominant light direction as [x, y, z] (normalized)
         */
        fun getDirectionEstimate(sh: FloatArray, out: FloatArray? = null): FloatArray

        /**
         * Estimates the color at a specific direction from spherical harmonics coefficients.
         *
         * Evaluates the SH basis at the given direction to estimate the environment
         * color from that direction.
         *
         * @param sh Spherical harmonics coefficients array
         * @param x Direction X component
         * @param y Direction Y component
         * @param z Direction Z component
         * @param out Optional FloatArray for result [r, g, b]; created if null
         * @return The estimated color at the given direction
         */
        fun getColorEstimate(sh: FloatArray, x: Double, y: Double, z: Double, out: FloatArray? = null): FloatArray
    }
}
