package io.github.erkko68.filament

/**
 * Material defines the visual appearance of a surface.
 *
 * Materials are created from a binary blob generated by the material compiler (matc).
 * A Material is a template from which [MaterialInstance] objects can be created.
 *
 * **Creating instances:**
 * Use [createInstance] to spawn an instance from this material. Instances inherit the material's
 * properties but can override parameters (color, texture, etc.) for per-object customization.
 * Always destroy instances with [Engine.destroy] before destroying the material.
 *
 * **Material compilation:**
 * Use [compile] to asynchronously compile specific material variants. This is useful for
 * precompiling variants you know will be used, reducing first-time rendering stalls.
 * After issuing multiple compile() calls, call [Engine.flush] so the backend can start
 * compilation work.
 */
expect class Material {
    /**
     * Shading model determines how light interacts with the material surface.
     *
     * - UNLIT: No lighting applied; emissive possible. Useful for UI, billboards, glow effects
     * - LIT: Standard physically-based lighting (default)
     * - SUBSURFACE: Subsurface scattering for thin materials (skin, leaves, paper)
     * - CLOTH: Cloth-specific lighting model for fabric appearance
     * - SPECULAR_GLOSSINESS: Legacy shading model (use LIT for new materials)
     */
    enum class Shading { UNLIT, LIT, SUBSURFACE, CLOTH, SPECULAR_GLOSSINESS }

    /**
     * Attribute interpolation type in the fragment shader.
     *
     * - SMOOTH: Smooth interpolation (default); values smoothly transition across primitives
     * - FLAT: Flat interpolation; values are constant per primitive (no interpolation)
     */
    enum class Interpolation { SMOOTH, FLAT }

    /**
     * Blending mode determines how a material's color is combined with the background.
     *
     * - OPAQUE: Material is opaque; fully solid (default)
     * - TRANSPARENT: Transparent with alpha pre-multiplication; affects diffuse lighting only
     * - ADD: Additive blending (e.g., hologram, glow)
     * - MASKED: Alpha-tested (either fully opaque or fully transparent per pixel)
     * - FADE: Transparent with alpha pre-multiplication; affects specular lighting
     * - MULTIPLY: Darkens what's behind it
     * - SCREEN: Brightens what's behind it
     */
    enum class BlendingMode { OPAQUE, TRANSPARENT, ADD, MASKED, FADE, MULTIPLY, SCREEN }

    /**
     * How transparent objects are rendered.
     *
     * - DEFAULT: Transparent object drawn honoring the raster state
     * - TWO_PASSES_ONE_SIDE: Object drawn in depth buffer, then color buffer with culling honored but depth test ignored
     * - TWO_PASSES_TWO_SIDES: Object drawn twice in color buffer (back faces, then front faces); culling ignored
     */
    enum class TransparencyMode { DEFAULT, TWO_PASSES_ONE_SIDE, TWO_PASSES_TWO_SIDES }

    /**
     * Refraction rendering mode.
     *
     * - NONE: No refraction
     * - CUBEMAP: Use cubemap for refraction (requires pre-captured environment)
     * - SCREEN_SPACE: Real-time screen-space refraction (can be expensive)
     */
    enum class RefractionMode { NONE, CUBEMAP, SCREEN_SPACE }

    /**
     * Type of refracted surface.
     *
     * - SOLID: Thick solid material (refraction assumes finite thickness)
     * - THIN: Thin material like glass (refraction assumes thin surface)
     */
    enum class RefractionType { SOLID, THIN }

    /**
     * Reflection rendering mode.
     *
     * - DEFAULT: Use standard reflection (cubemap or IBL)
     * - SCREEN_SPACE: Real-time screen-space reflections (can be expensive)
     */
    enum class ReflectionMode { DEFAULT, SCREEN_SPACE }

    /**
     * Vertex domain specifies which coordinate space vertices are defined in.
     *
     * - OBJECT: Vertices in object space (default)
     * - WORLD: Vertices in world space
     * - VIEW: Vertices in view/camera space
     * - DEVICE: Vertices in normalized device coordinates ([-1, 1])
     */
    enum class VertexDomain { OBJECT, WORLD, VIEW, DEVICE }

    /**
     * Culling mode determines which faces are rendered.
     *
     * - NONE: Both front and back faces rendered (disables culling)
     * - FRONT: Cull front faces; only back faces rendered
     * - BACK: Cull back faces; only front faces rendered (default)
     * - FRONT_AND_BACK: Cull all faces (usually used for testing or special effects)
     */
    enum class CullingMode { NONE, FRONT, BACK, FRONT_AND_BACK }

    /**
     * Priority queue for asynchronous material compilation.
     *
     * - CRITICAL: Highest priority; compiles immediately
     * - HIGH: High priority; compiles before LOW queue
     * - LOW: Low priority; compiles last
     *
     * @see compile
     */
    enum class CompilerPriorityQueue { CRITICAL, HIGH, LOW }

    /**
     * UBO batching mode controls whether material instances share uniform buffers.
     *
     * - DEFAULT: Use engine settings; if UBO batching is enabled and material domain is SURFACE, enable it
     * - DISABLED: Disable UBO batching for this material (each instance gets its own uniform buffer)
     */
    enum class UboBatchingMode { DEFAULT, DISABLED }

    /**
     * User variant filter bits for material compilation.
     *
     * These bits control which material variants are compiled. Using only required variants
     * saves compilation time and memory. For example, if your app doesn't use stereoscopic rendering,
     * clear the STE bit.
     */
    class UserVariantFilterBit {
        companion object {
            /** Variant for directional lighting */
            val DIRECTIONAL_LIGHTING: Int
            /** Variant for dynamic (local) lighting */
            val DYNAMIC_LIGHTING: Int
            /** Variant for shadow-receiving objects */
            val SHADOW_RECEIVER: Int
            /** Variant for skinned/skeletal animation */
            val SKINNING: Int
            /** Variant for fog effects */
            val FOG: Int
            /** Variant for Variance Shadow Maps */
            val VSM: Int
            /** Variant for Screen-Space Reflections */
            val SSR: Int
            /** Variant for stereoscopic rendering */
            val STE: Int
            /** All variants combined */
            val ALL: Int
        }
    }

    /**
     * Holds metadata about a material parameter.
     *
     * Parameters are created during material compilation and define customizable properties
     * like textures, colors, or numeric values that can be set per instance.
     */
    class Parameter(
        name: String,
        type: Type,
        precision: Precision,
        count: Int
    ) {
        /** Name of the parameter as defined in the material */
        val name: String
        /** Data type of the parameter */
        val type: Type
        /** Precision (if a numeric type) */
        val precision: Precision
        /** Array count (1 if not an array) */
        val count: Int

        /**
         * Parameter data types.
         *
         * - BOOL/BOOL2/BOOL3/BOOL4: Boolean scalar or vector
         * - FLOAT/FLOAT2/FLOAT3/FLOAT4: Floating-point scalar or vector
         * - INT/INT2/INT3/INT4: Signed integer scalar or vector
         * - UINT/UINT2/UINT3/UINT4: Unsigned integer scalar or vector
         * - MAT3/MAT4: 3x3 or 4x4 floating-point matrix
         * - SAMPLER_2D/SAMPLER_2D_ARRAY/SAMPLER_CUBEMAP/SAMPLER_EXTERNAL/SAMPLER_3D: Texture sampler
         * - SUBPASS_INPUT: Input attachment for rendering
         */
        enum class Type {
            BOOL, BOOL2, BOOL3, BOOL4,
            FLOAT, FLOAT2, FLOAT3, FLOAT4,
            INT, INT2, INT3, INT4,
            UINT, UINT2, UINT3, UINT4,
            MAT3, MAT4,
            SAMPLER_2D, SAMPLER_2D_ARRAY, SAMPLER_CUBEMAP, SAMPLER_EXTERNAL, SAMPLER_3D,
            SUBPASS_INPUT
        }

        /**
         * Precision level for numeric parameters.
         *
         * - LOW: Low precision (may reduce quality but improve performance)
         * - MEDIUM: Medium precision
         * - HIGH: High precision
         * - DEFAULT: Use engine default
         */
        enum class Precision { LOW, MEDIUM, HIGH, DEFAULT }
    }

    /**
     * Builder for creating Material objects from compiled material packages.
     *
     * The Builder takes a material package (binary blob from the matc compiler) and
     * configures rendering quality and batching options before building the final Material.
     */
    class Builder() {
        /**
         * Shadow sampling quality affects how soft shadows are rendered.
         *
         * - HARD: 2x2 PCF (Percentage Closer Filtering); faster but harder shadows
         * - LOW: 3x3 Gaussian filter; slower but softer, smoother shadows
         */
        enum class ShadowSamplingQuality { HARD, LOW }

        /**
         * Specifies the material package data (compiled binary from matc compiler).
         *
         * @param data Material package bytecode; must stay valid until build() is called
         * @return This Builder, for chaining calls
         */
        fun payload(data: ByteArray): Builder

        /**
         * Sets the quality of indirect light computations via spherical harmonics.
         *
         * This is only applied if the material is lit and in the surface domain.
         * More bands = higher quality but more computation. The spherical harmonics
         * are used to compute irradiance from an [IndirectLight].
         *
         * @param shBandCount Number of spherical harmonic bands (1, 2, or 3; default: 3)
         * @return This Builder, for chaining calls
         *
         * @see IndirectLight
         */
        fun sphericalHarmonicsBandCount(shBandCount: Int): Builder

        /**
         * Sets the quality of shadow sampling for this material.
         *
         * This is only applied if the material is lit and in the surface domain.
         *
         * @param quality Shadow sampling quality (HARD for PCF, LOW for Gaussian filter)
         * @return This Builder, for chaining calls
         */
        fun shadowSamplingQuality(quality: ShadowSamplingQuality): Builder

        /**
         * Sets the batching mode for instances created from this material.
         *
         * UBO batching allows multiple material instances to share a single uniform buffer,
         * reducing memory and state changes. When enabled, instances are automatically
         * batched together during rendering.
         *
         * @param mode DEFAULT to use engine settings, or DISABLED to disable per-material
         * @return This Builder, for chaining calls
         */
        fun uboBatching(mode: UboBatchingMode): Builder

        /**
         * Creates the Material and returns it.
         *
         * @param engine Engine to associate this Material with
         * @return The newly created Material, or null if build failed (when exceptions disabled)
         */
        fun build(engine: Engine): Material
    }

    /**
     * Asynchronously compiles specified variants of this material.
     *
     * After issuing multiple compile() calls, call [Engine.flush] so the backend can start
     * work as soon as possible. The callback is guaranteed to be called on the main thread
     * after compilation completes.
     *
     * If the same variant is scheduled multiple times, the first scheduling takes precedence.
     *
     * **Note:** Only compile variants you'll actually use. For example, if your app doesn't
     * use stereoscopic rendering, don't compile the STE variant. Use [UserVariantFilterBit]
     * to specify which variants to compile.
     *
     * @param priority Queue to use (CRITICAL, HIGH, or LOW)
     * @param variants Variants to compile (bitmask of UserVariantFilterBit values)
     * @param callback Optional callback invoked on main thread when compilation completes
     */
    fun compile(priority: CompilerPriorityQueue, variants: Int, callback: (() -> Unit)? = null)

    /**
     * Creates a new instance of this material.
     *
     * Instances inherit all material properties but can override parameters. Multiple
     * instances can be created from a single material. Always destroy instances with
     * [Engine.destroy] when no longer needed.
     *
     * @return A new MaterialInstance with default parameters
     */
    fun createInstance(): MaterialInstance

    /**
     * Creates a new instance of this material with an optional name.
     *
     * The name can be used for debugging/profiling purposes.
     *
     * @param name Optional name for the instance (if null, inherits material name)
     * @return A new MaterialInstance with the given name
     */
    fun createInstance(name: String): MaterialInstance

    /**
     * Returns this material's default instance.
     *
     * The default instance is used by the material itself for setDefaultParameter() calls.
     * Changes to the default instance affect all MaterialInstances that don't override those
     * parameters.
     *
     * @return The default MaterialInstance (owned by this Material)
     */
    fun getDefaultInstance(): MaterialInstance
    
    /**
     * Gets the name of this material.
     * @return Material name as a string
     */
    fun getName(): String

    /**
     * Gets the shading model of this material.
     * @return Shading type (UNLIT, LIT, SUBSURFACE, CLOTH, or SPECULAR_GLOSSINESS)
     */
    fun getShading(): Shading

    /**
     * Gets the interpolation mode for vertex attributes in the fragment shader.
     * @return Interpolation type (SMOOTH or FLAT)
     */
    fun getInterpolation(): Interpolation

    /**
     * Gets the blending mode of this material.
     * @return Blending mode determining how this material's color combines with the background
     */
    fun getBlendingMode(): BlendingMode

    /**
     * Gets the transparency mode for transparent materials.
     *
     * This value only makes sense when blending mode is TRANSPARENT or FADE.
     *
     * @return Transparency rendering mode
     */
    fun getTransparencyMode(): TransparencyMode

    /**
     * Gets the refraction mode (if any) used by this material.
     * @return Refraction mode (NONE, CUBEMAP, or SCREEN_SPACE)
     */
    fun getRefractionMode(): RefractionMode

    /**
     * Gets the refraction type for refracted surfaces.
     * @return Refraction type (SOLID or THIN)
     */
    fun getRefractionType(): RefractionType

    /**
     * Gets the reflection mode used by this material.
     * @return Reflection mode (DEFAULT or SCREEN_SPACE)
     */
    fun getReflectionMode(): ReflectionMode

    /**
     * Gets the vertex domain (coordinate space) of this material.
     * @return Vertex domain (OBJECT, WORLD, VIEW, or DEVICE)
     */
    fun getVertexDomain(): VertexDomain

    /**
     * Gets the culling mode of this material.
     * @return Culling mode (NONE, FRONT, BACK, or FRONT_AND_BACK)
     */
    fun getCullingMode(): CullingMode

    /**
     * Indicates whether instances of this material write to the color buffer (enabled by default).
     * @return true if color writes are enabled
     */
    fun isColorWriteEnabled(): Boolean

    /**
     * Indicates whether instances of this material write to the depth buffer (enabled by default).
     * @return true if depth writes are enabled
     */
    fun isDepthWriteEnabled(): Boolean

    /**
     * Indicates whether instances of this material perform depth testing (enabled by default).
     * @return true if depth testing is enabled
     */
    fun isDepthCullingEnabled(): Boolean

    /**
     * Indicates whether this material is double-sided.
     *
     * If false (single-sided, default), back faces are culled. If true, both front and back
     * faces are rendered.
     *
     * @return true if material is double-sided
     */
    fun isDoubleSided(): Boolean

    /**
     * Indicates whether this material uses alpha-to-coverage.
     *
     * Alpha-to-coverage converts alpha values to a coverage mask for MSAA, providing
     * better quality transparent edges with MSAA enabled.
     *
     * @return true if alpha-to-coverage is enabled
     */
    fun isAlphaToCoverageEnabled(): Boolean

    /**
     * Gets the alpha mask threshold used when blending mode is MASKED.
     *
     * Pixels with alpha >= threshold are opaque; below threshold are transparent.
     * Range: [0, 1].
     *
     * @return Alpha threshold value
     */
    fun getMaskThreshold(): Float

    /**
     * Gets the screen-space variance for specular anti-aliasing (if enabled).
     *
     * Lower values reduce aliasing but may slightly blur specular highlights.
     *
     * @return Variance value between 0 and 1
     */
    fun getSpecularAntiAliasingVariance(): Float

    /**
     * Gets the clamping threshold for specular anti-aliasing (if enabled).
     *
     * Clamps specular aliasing reduction to avoid over-blurring.
     *
     * @return Threshold value between 0 and 1
     */
    fun getSpecularAntiAliasingThreshold(): Float

    /**
     * Gets the minimum required feature level for this material.
     * @return Feature level (e.g., FEATURE_LEVEL_0, FEATURE_LEVEL_1, FEATURE_LEVEL_2, or FEATURE_LEVEL_3)
     */
    fun getFeatureLevel(): Engine.FeatureLevel
    
    /**
     * Returns the number of parameters declared by this material.
     * @return Parameter count (can be 0 if the material has no parameters)
     */
    fun getParameterCount(): Int

    /**
     * Gets information about all parameters declared by this material.
     * @return List of Parameter metadata objects
     */
    fun getParameters(): List<Parameter>

    /**
     * Checks whether a parameter with the given name exists on this material.
     * @param name Parameter name to check
     * @return true if the parameter exists
     */
    fun hasParameter(name: String): Boolean

    /**
     * Gets the transform name associated with a sampler parameter.
     *
     * Some samplers can have associated texture coordinate transforms (scale, rotation, etc.).
     * This method returns the name of the transform parameter if it exists.
     *
     * @param samplerName The name of a sampler parameter
     * @return Transform parameter name if it exists, or null if not
     */
    fun getParameterTransformName(samplerName: String): String?

    /**
     * Sets a boolean parameter on this material's default instance.
     *
     * @param name The parameter name
     * @param value The boolean value
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, value: Boolean)

    /**
     * Sets a float parameter on this material's default instance.
     *
     * @param name The parameter name
     * @param value The float value
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, value: Float)

    /**
     * Sets an integer parameter on this material's default instance.
     *
     * @param name The parameter name
     * @param value The integer value
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, value: Int)

    /**
     * Sets a 2D vector parameter on this material's default instance.
     *
     * @param name The parameter name
     * @param x X component
     * @param y Y component
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, x: Float, y: Float)

    /**
     * Sets a 3D vector parameter on this material's default instance.
     *
     * @param name The parameter name
     * @param x X component
     * @param y Y component
     * @param z Z component
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, x: Float, y: Float, z: Float)

    /**
     * Sets a 4D vector parameter on this material's default instance.
     *
     * @param name The parameter name
     * @param x X component
     * @param y Y component
     * @param z Z component
     * @param w W component
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, x: Float, y: Float, z: Float, w: Float)

    /**
     * Gets the set of vertex attributes required by this material.
     *
     * Use this to determine which attributes your vertex buffers must provide.
     * If a required attribute is missing, rendering will fail or produce incorrect results.
     *
     * @return Set of required VertexAttribute values (e.g., POSITION, TANGENTS, UV0)
     */
    fun getRequiredAttributes(): Set<VertexBuffer.VertexAttribute>
}
