#ifndef FILAMENT_C_MATERIAL_ENUMS_H
#define FILAMENT_C_MATERIAL_ENUMS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FILA_MATERIAL_VERSION 70u
#define FILA_RELEASED_MATERIAL_API_LEVEL 1u
#define FILA_UNSTABLE_MATERIAL_API_LEVEL 2u

typedef enum FilaMaterialShading {
    FILA_MATERIAL_SHADING_UNLIT = 0,
    FILA_MATERIAL_SHADING_LIT = 1,
    FILA_MATERIAL_SHADING_SUBSURFACE = 2,
    FILA_MATERIAL_SHADING_CLOTH = 3,
    FILA_MATERIAL_SHADING_SPECULAR_GLOSSINESS = 4,
} FilaMaterialShading;

typedef enum FilaMaterialInterpolation {
    FILA_MATERIAL_INTERPOLATION_SMOOTH = 0,
    FILA_MATERIAL_INTERPOLATION_FLAT = 1,
} FilaMaterialInterpolation;

typedef enum FilaMaterialShaderQuality {
    FILA_MATERIAL_SHADER_QUALITY_DEFAULT = -1,
    FILA_MATERIAL_SHADER_QUALITY_LOW = 0,
    FILA_MATERIAL_SHADER_QUALITY_NORMAL = 1,
    FILA_MATERIAL_SHADER_QUALITY_HIGH = 2,
} FilaMaterialShaderQuality;

typedef enum FilaMaterialBlendingMode {
    FILA_MATERIAL_BLENDING_MODE_OPAQUE = 0,
    FILA_MATERIAL_BLENDING_MODE_TRANSPARENT = 1,
    FILA_MATERIAL_BLENDING_MODE_ADD = 2,
    FILA_MATERIAL_BLENDING_MODE_MASKED = 3,
    FILA_MATERIAL_BLENDING_MODE_FADE = 4,
    FILA_MATERIAL_BLENDING_MODE_MULTIPLY = 5,
    FILA_MATERIAL_BLENDING_MODE_SCREEN = 6,
    FILA_MATERIAL_BLENDING_MODE_CUSTOM = 7,
} FilaMaterialBlendingMode;

typedef enum FilaMaterialTransparencyMode {
    FILA_MATERIAL_TRANSPARENCY_MODE_DEFAULT = 0,
    FILA_MATERIAL_TRANSPARENCY_MODE_TWO_PASSES_ONE_SIDE = 1,
    FILA_MATERIAL_TRANSPARENCY_MODE_TWO_PASSES_TWO_SIDES = 2,
} FilaMaterialTransparencyMode;

typedef enum FilaMaterialVertexDomain {
    FILA_MATERIAL_VERTEX_DOMAIN_OBJECT = 0,
    FILA_MATERIAL_VERTEX_DOMAIN_WORLD = 1,
    FILA_MATERIAL_VERTEX_DOMAIN_VIEW = 2,
    FILA_MATERIAL_VERTEX_DOMAIN_DEVICE = 3,
} FilaMaterialVertexDomain;

typedef enum FilaMaterialDomain {
    FILA_MATERIAL_DOMAIN_SURFACE = 0,
    FILA_MATERIAL_DOMAIN_POST_PROCESS = 1,
    FILA_MATERIAL_DOMAIN_COMPUTE = 2,
} FilaMaterialDomain;

typedef enum FilaMaterialSpecularAmbientOcclusion {
    FILA_MATERIAL_SPECULAR_AMBIENT_OCCLUSION_NONE = 0,
    FILA_MATERIAL_SPECULAR_AMBIENT_OCCLUSION_SIMPLE = 1,
    FILA_MATERIAL_SPECULAR_AMBIENT_OCCLUSION_BENT_NORMALS = 2,
} FilaMaterialSpecularAmbientOcclusion;

typedef enum FilaMaterialRefractionMode {
    FILA_MATERIAL_REFRACTION_MODE_NONE = 0,
    FILA_MATERIAL_REFRACTION_MODE_CUBEMAP = 1,
    FILA_MATERIAL_REFRACTION_MODE_SCREEN_SPACE = 2,
} FilaMaterialRefractionMode;

typedef enum FilaMaterialRefractionType {
    FILA_MATERIAL_REFRACTION_TYPE_SOLID = 0,
    FILA_MATERIAL_REFRACTION_TYPE_THIN = 1,
} FilaMaterialRefractionType;

typedef enum FilaMaterialReflectionMode {
    FILA_MATERIAL_REFLECTION_MODE_DEFAULT = 0,
    FILA_MATERIAL_REFLECTION_MODE_SCREEN_SPACE = 1,
} FilaMaterialReflectionMode;

typedef enum FilaMaterialUserVariantFilterBit {
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_DIRECTIONAL_LIGHTING = 0x01,
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_DYNAMIC_LIGHTING = 0x02,
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_SHADOW_RECEIVER = 0x04,
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_SKINNING = 0x08,
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_FOG = 0x10,
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_VSM = 0x20,
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_SSR = 0x40,
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_STE = 0x80,
    FILA_MATERIAL_USER_VARIANT_FILTER_BIT_ALL = 0xFF,
} FilaMaterialUserVariantFilterBit;

#ifdef __cplusplus
}
#endif

#endif // FILAMENT_C_MATERIAL_ENUMS_H

