#ifndef FILAMENT_C_MATERIAL_CHUNK_TYPE_H
#define FILAMENT_C_MATERIAL_CHUNK_TYPE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FILA_MATERIAL_CHUNK8(a, b, c, d, e, f, g, h) \
    ((((uint64_t)(a) & 0xFFull) << 56) | (((uint64_t)(b) & 0xFFull) << 48) | \
     (((uint64_t)(c) & 0xFFull) << 40) | (((uint64_t)(d) & 0xFFull) << 32) | \
     (((uint64_t)(e) & 0xFFull) << 24) | (((uint64_t)(f) & 0xFFull) << 16) | \
     (((uint64_t)(g) & 0xFFull) << 8)  | (((uint64_t)(h) & 0xFFull)))

typedef enum FilaMaterialChunkType {
    FILA_MATERIAL_CHUNK_TYPE_UNKNOWN = FILA_MATERIAL_CHUNK8('U','N','K','N','O','W','N',' '),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_UIB = FILA_MATERIAL_CHUNK8('M','A','T','_','U','I','B',' '),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SIB = FILA_MATERIAL_CHUNK8('M','A','T','_','S','I','B',' '),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SUBPASS = FILA_MATERIAL_CHUNK8('M','A','T','_','S','U','B',' '),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_GLSL = FILA_MATERIAL_CHUNK8('M','A','T','_','G','L','S','L'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_ESSL1 = FILA_MATERIAL_CHUNK8('M','A','T','_','E','S','S','1'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SPIRV = FILA_MATERIAL_CHUNK8('M','A','T','_','S','P','I','R'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_METAL = FILA_MATERIAL_CHUNK8('M','A','T','_','M','E','T','L'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_WGSL = FILA_MATERIAL_CHUNK8('M','A','T','_','W','G','S','L'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_METAL_LIBRARY = FILA_MATERIAL_CHUNK8('M','A','T','_','M','L','I','B'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SHADER_MODELS = FILA_MATERIAL_CHUNK8('M','A','T','_','S','M','D','L'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_BINDING_UNIFORM_INFO = FILA_MATERIAL_CHUNK8('M','A','T','_','U','F','R','M'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_ATTRIBUTE_INFO = FILA_MATERIAL_CHUNK8('M','A','T','_','A','T','T','R'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_DESCRIPTOR_BINDINGS_INFO = FILA_MATERIAL_CHUNK8('M','A','T','_','D','B','D','I'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_DESCRIPTOR_SET_LAYOUT_INFO = FILA_MATERIAL_CHUNK8('M','A','T','_','D','S','L','I'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_PROPERTIES = FILA_MATERIAL_CHUNK8('M','A','T','_','P','R','O','P'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_CONSTANTS = FILA_MATERIAL_CHUNK8('M','A','T','_','C','O','N','S'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_PUSH_CONSTANTS = FILA_MATERIAL_CHUNK8('M','A','T','_','P','C','O','N'),

    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_NAME = FILA_MATERIAL_CHUNK8('M','A','T','_','N','A','M','E'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_VERSION = FILA_MATERIAL_CHUNK8('M','A','T','_','V','E','R','S'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_COMPILATION_PARAMETERS = FILA_MATERIAL_CHUNK8('M','A','T','_','C','P','R','M'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_CACHE_ID = FILA_MATERIAL_CHUNK8('M','A','T','_','U','U','I','D'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_FEATURE_LEVEL = FILA_MATERIAL_CHUNK8('M','A','T','_','F','E','A','T'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SHADING = FILA_MATERIAL_CHUNK8('M','A','T','_','S','H','A','D'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_BLENDING_MODE = FILA_MATERIAL_CHUNK8('M','A','T','_','B','L','E','N'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_BLEND_FUNCTION = FILA_MATERIAL_CHUNK8('M','A','T','_','B','L','F','N'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_TRANSPARENCY_MODE = FILA_MATERIAL_CHUNK8('M','A','T','_','T','R','M','D'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_MASK_THRESHOLD = FILA_MATERIAL_CHUNK8('M','A','T','_','T','H','R','S'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SHADOW_MULTIPLIER = FILA_MATERIAL_CHUNK8('M','A','T','_','S','H','M','L'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SPECULAR_ANTI_ALIASING = FILA_MATERIAL_CHUNK8('M','A','T','_','S','P','A','A'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SPECULAR_ANTI_ALIASING_VARIANCE = FILA_MATERIAL_CHUNK8('M','A','T','_','S','V','A','R'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SPECULAR_ANTI_ALIASING_THRESHOLD = FILA_MATERIAL_CHUNK8('M','A','T','_','S','T','H','R'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_CLEAR_COAT_IOR_CHANGE = FILA_MATERIAL_CHUNK8('M','A','T','_','C','I','O','R'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_DOMAIN = FILA_MATERIAL_CHUNK8('M','A','T','_','D','O','M','N'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_VARIANT_FILTER_MASK = FILA_MATERIAL_CHUNK8('M','A','T','_','V','F','L','T'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_REFRACTION = FILA_MATERIAL_CHUNK8('M','A','T','_','R','E','F','M'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_REFRACTION_TYPE = FILA_MATERIAL_CHUNK8('M','A','T','_','R','E','F','T'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_REFLECTION_MODE = FILA_MATERIAL_CHUNK8('M','A','T','_','R','E','F','L'),

    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_REQUIRED_ATTRIBUTES = FILA_MATERIAL_CHUNK8('M','A','T','_','R','E','Q','A'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_DOUBLE_SIDED_SET = FILA_MATERIAL_CHUNK8('M','A','T','_','D','O','S','S'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_DOUBLE_SIDED = FILA_MATERIAL_CHUNK8('M','A','T','_','D','O','S','I'),

    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_COLOR_WRITE = FILA_MATERIAL_CHUNK8('M','A','T','_','C','W','R','I'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_DEPTH_WRITE_SET = FILA_MATERIAL_CHUNK8('M','A','T','_','D','E','W','S'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_DEPTH_WRITE = FILA_MATERIAL_CHUNK8('M','A','T','_','D','W','R','I'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_DEPTH_TEST = FILA_MATERIAL_CHUNK8('M','A','T','_','D','T','E','S'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_INSTANCED = FILA_MATERIAL_CHUNK8('M','A','T','_','I','N','S','T'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_CULLING_MODE = FILA_MATERIAL_CHUNK8('M','A','T','_','C','U','M','O'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_ALPHA_TO_COVERAGE_SET = FILA_MATERIAL_CHUNK8('M','A','T','_','A','2','C','S'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_ALPHA_TO_COVERAGE = FILA_MATERIAL_CHUNK8('M','A','T','_','A','2','C','O'),

    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_HAS_CUSTOM_DEPTH_SHADER = FILA_MATERIAL_CHUNK8('M','A','T','_','C','S','D','P'),

    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_VERTEX_DOMAIN = FILA_MATERIAL_CHUNK8('M','A','T','_','V','E','D','O'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_INTERPOLATION = FILA_MATERIAL_CHUNK8('M','A','T','_','I','N','T','R'),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_STEREOSCOPIC_TYPE = FILA_MATERIAL_CHUNK8('M','A','T','_','S','T','E','R'),

    FILA_MATERIAL_CHUNK_TYPE_DICTIONARY_TEXT = FILA_MATERIAL_CHUNK8('D','I','C','_','T','E','X','T'),
    FILA_MATERIAL_CHUNK_TYPE_DICTIONARY_SPIRV = FILA_MATERIAL_CHUNK8('D','I','C','_','S','P','I','R'),
    FILA_MATERIAL_CHUNK_TYPE_DICTIONARY_METAL_LIBRARY = FILA_MATERIAL_CHUNK8('D','I','C','_','M','L','I','B'),

    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_CRC32 = FILA_MATERIAL_CHUNK8('M','A','T','_','C','R','C',' '),
    FILA_MATERIAL_CHUNK_TYPE_MATERIAL_SOURCE = FILA_MATERIAL_CHUNK8('M','A','T','_','S','R','C',' '),
} FilaMaterialChunkType;

#ifdef __cplusplus
}
#endif

#endif // FILAMENT_C_MATERIAL_CHUNK_TYPE_H

