#ifndef FILAMENT_C_BACKEND_DRIVERENUMS_H
#define FILAMENT_C_BACKEND_DRIVERENUMS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FILA_BACKEND_HANDLE_NULL 0xFFFFFFFFu

typedef enum FilaBackendTargetBufferFlags {
    FILA_BACKEND_TARGET_BUFFER_NONE = 0x00000000u,
    FILA_BACKEND_TARGET_BUFFER_COLOR0 = 0x00000001u,
    FILA_BACKEND_TARGET_BUFFER_COLOR1 = 0x00000002u,
    FILA_BACKEND_TARGET_BUFFER_COLOR2 = 0x00000004u,
    FILA_BACKEND_TARGET_BUFFER_COLOR3 = 0x00000008u,
    FILA_BACKEND_TARGET_BUFFER_COLOR4 = 0x00000010u,
    FILA_BACKEND_TARGET_BUFFER_COLOR5 = 0x00000020u,
    FILA_BACKEND_TARGET_BUFFER_COLOR6 = 0x00000040u,
    FILA_BACKEND_TARGET_BUFFER_COLOR7 = 0x00000080u,
    FILA_BACKEND_TARGET_BUFFER_COLOR = 0x00000001u,
    FILA_BACKEND_TARGET_BUFFER_COLOR_ALL = 0x000000FFu,
    FILA_BACKEND_TARGET_BUFFER_DEPTH = 0x10000000u,
    FILA_BACKEND_TARGET_BUFFER_STENCIL = 0x20000000u,
    FILA_BACKEND_TARGET_BUFFER_DEPTH_AND_STENCIL = 0x30000000u,
    FILA_BACKEND_TARGET_BUFFER_ALL = 0x300000FFu,
} FilaBackendTargetBufferFlags;

typedef enum FilaBackendTextureCubemapFace {
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_X = 0,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_X = 1,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_Y = 2,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_Y = 3,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_Z = 4,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_Z = 5,
} FilaBackendTextureCubemapFace;

FilaBackendTargetBufferFlags FilaBackendTargetBufferFlags_at(size_t index);

#ifdef __cplusplus
}
#endif

#endif // FILAMENT_C_BACKEND_DRIVERENUMS_H

