#ifndef FILAMENT_C_BACKEND_DRIVERENUMS_H
#define FILAMENT_C_BACKEND_DRIVERENUMS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FILA_BACKEND_HANDLE_NULL 0xFFFFFFFFu

typedef enum FilaBackendFeatureLevel {
    FILA_BACKEND_FEATURE_LEVEL_0 = 0,
    FILA_BACKEND_FEATURE_LEVEL_1 = 1,
    FILA_BACKEND_FEATURE_LEVEL_2 = 2,
    FILA_BACKEND_FEATURE_LEVEL_3 = 3,
} FilaBackendFeatureLevel;

typedef enum FilaBackendBackend {
    FILA_BACKEND_DEFAULT = 0,
    FILA_BACKEND_OPENGL = 1,
    FILA_BACKEND_VULKAN = 2,
    FILA_BACKEND_METAL = 3,
    FILA_BACKEND_WEBGPU = 4,
    FILA_BACKEND_NOOP = 5,
} FilaBackendBackend;

typedef enum FilaBackendTimerQueryResult {
    FILA_BACKEND_TIMER_QUERY_ERROR = -1,
    FILA_BACKEND_TIMER_QUERY_NOT_READY = 0,
    FILA_BACKEND_TIMER_QUERY_AVAILABLE = 1,
} FilaBackendTimerQueryResult;

typedef enum FilaBackendShaderLanguage {
    FILA_BACKEND_SHADER_LANGUAGE_UNSPECIFIED = -1,
    FILA_BACKEND_SHADER_LANGUAGE_ESSL1 = 0,
    FILA_BACKEND_SHADER_LANGUAGE_ESSL3 = 1,
    FILA_BACKEND_SHADER_LANGUAGE_SPIRV = 2,
    FILA_BACKEND_SHADER_LANGUAGE_MSL = 3,
    FILA_BACKEND_SHADER_LANGUAGE_METAL_LIBRARY = 4,
    FILA_BACKEND_SHADER_LANGUAGE_WGSL = 5,
} FilaBackendShaderLanguage;

typedef enum FilaBackendShaderStage {
    FILA_BACKEND_SHADER_STAGE_VERTEX = 0,
    FILA_BACKEND_SHADER_STAGE_FRAGMENT = 1,
    FILA_BACKEND_SHADER_STAGE_COMPUTE = 2,
} FilaBackendShaderStage;

typedef enum FilaBackendShaderStageFlags {
    FILA_BACKEND_SHADER_STAGE_FLAGS_NONE = 0,
    FILA_BACKEND_SHADER_STAGE_FLAGS_VERTEX = 0x1,
    FILA_BACKEND_SHADER_STAGE_FLAGS_FRAGMENT = 0x2,
    FILA_BACKEND_SHADER_STAGE_FLAGS_COMPUTE = 0x4,
    FILA_BACKEND_SHADER_STAGE_FLAGS_ALL = 0x7,
} FilaBackendShaderStageFlags;

typedef enum FilaBackendTargetBufferFlags {
    FILA_BACKEND_TARGET_BUFFER_NONE = 0x00000000u,
    FILA_BACKEND_TARGET_BUFFER_COLOR0 = 0x00000001u,
    FILA_BACKEND_TARGET_BUFFER_COLOR1 = 0x00000002u,
    FILA_BACKEND_TARGET_BUFFER_COLOR2 = 0x00000004u,
    FILA_BACKEND_TARGET_BUFFER_COLOR3 = 0x00000008u,
    FILA_BACKEND_TARGET_BUFFER_COLOR4 = 0x00000010u,
    FILA_BACKEND_TARGET_BUFFER_COLOR5 = 0x00000020u,
    FILA_BACKEND_TARGET_BUFFER_COLOR6 = 0x00000040u,
    FILA_BACKEND_TARGET_BUFFER_COLOR7 = 0x00000080u,
    FILA_BACKEND_TARGET_BUFFER_COLOR = 0x00000001u,
    FILA_BACKEND_TARGET_BUFFER_COLOR_ALL = 0x000000FFu,
    FILA_BACKEND_TARGET_BUFFER_DEPTH = 0x10000000u,
    FILA_BACKEND_TARGET_BUFFER_STENCIL = 0x20000000u,
    FILA_BACKEND_TARGET_BUFFER_DEPTH_AND_STENCIL = 0x30000000u,
    FILA_BACKEND_TARGET_BUFFER_ALL = 0x300000FFu,
} FilaBackendTargetBufferFlags;

typedef enum FilaBackendTextureCubemapFace {
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_X = 0,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_X = 1,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_Y = 2,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_Y = 3,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_Z = 4,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_Z = 5,
} FilaBackendTextureCubemapFace;

typedef enum FilaBackendRenderTargetAttachmentPoint {
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR0 = 0,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR1 = 1,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR2 = 2,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR3 = 3,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR4 = 4,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR5 = 5,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR6 = 6,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR7 = 7,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_DEPTH = 8,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR = 0,
} FilaBackendRenderTargetAttachmentPoint;

typedef enum FilaBackendTextureUsage {
    FILA_BACKEND_TEXTURE_USAGE_NONE = 0x0000,
    FILA_BACKEND_TEXTURE_USAGE_COLOR_ATTACHMENT = 0x0001,
    FILA_BACKEND_TEXTURE_USAGE_DEPTH_ATTACHMENT = 0x0002,
    FILA_BACKEND_TEXTURE_USAGE_STENCIL_ATTACHMENT = 0x0004,
    FILA_BACKEND_TEXTURE_USAGE_UPLOADABLE = 0x0008,
    FILA_BACKEND_TEXTURE_USAGE_SAMPLEABLE = 0x0010,
    FILA_BACKEND_TEXTURE_USAGE_SUBPASS_INPUT = 0x0020,
    FILA_BACKEND_TEXTURE_USAGE_BLIT_SRC = 0x0040,
    FILA_BACKEND_TEXTURE_USAGE_BLIT_DST = 0x0080,
    FILA_BACKEND_TEXTURE_USAGE_PROTECTED = 0x0100,
    FILA_BACKEND_TEXTURE_USAGE_GEN_MIPMAPPABLE = 0x0200,
    FILA_BACKEND_TEXTURE_USAGE_DEFAULT = 0x0018,
    FILA_BACKEND_TEXTURE_USAGE_ALL_ATTACHMENTS = 0x0027,
} FilaBackendTextureUsage;

typedef enum FilaBackendBufferUsage {
    FILA_BACKEND_BUFFER_USAGE_STATIC = 0,
    FILA_BACKEND_BUFFER_USAGE_DYNAMIC = 1,
    FILA_BACKEND_BUFFER_USAGE_DYNAMIC_BIT = 0x1,
    FILA_BACKEND_BUFFER_USAGE_SHARED_WRITE_BIT = 0x04,
} FilaBackendBufferUsage;

typedef enum FilaBackendMapBufferAccessFlags {
    FILA_BACKEND_MAP_BUFFER_ACCESS_WRITE_BIT = 0x2,
    FILA_BACKEND_MAP_BUFFER_ACCESS_INVALIDATE_RANGE_BIT = 0x4,
} FilaBackendMapBufferAccessFlags;

typedef enum FilaBackendFenceStatus {
    FILA_BACKEND_FENCE_STATUS_ERROR = -1,
    FILA_BACKEND_FENCE_STATUS_CONDITION_SATISFIED = 0,
    FILA_BACKEND_FENCE_STATUS_TIMEOUT_EXPIRED = 1,
} FilaBackendFenceStatus;

typedef enum FilaBackendShaderModel {
    FILA_BACKEND_SHADER_MODEL_MOBILE = 1,
    FILA_BACKEND_SHADER_MODEL_DESKTOP = 2,
} FilaBackendShaderModel;

typedef enum FilaBackendPrimitiveType {
    FILA_BACKEND_PRIMITIVE_TYPE_POINTS = 0,
    FILA_BACKEND_PRIMITIVE_TYPE_LINES = 1,
    FILA_BACKEND_PRIMITIVE_TYPE_LINE_STRIP = 3,
    FILA_BACKEND_PRIMITIVE_TYPE_TRIANGLES = 4,
    FILA_BACKEND_PRIMITIVE_TYPE_TRIANGLE_STRIP = 5,
} FilaBackendPrimitiveType;

typedef enum FilaBackendSamplerType {
    FILA_BACKEND_SAMPLER_TYPE_2D = 0,
    FILA_BACKEND_SAMPLER_TYPE_2D_ARRAY = 1,
    FILA_BACKEND_SAMPLER_TYPE_CUBEMAP = 2,
    FILA_BACKEND_SAMPLER_TYPE_EXTERNAL = 3,
    FILA_BACKEND_SAMPLER_TYPE_3D = 4,
    FILA_BACKEND_SAMPLER_TYPE_CUBEMAP_ARRAY = 5,
} FilaBackendSamplerType;

typedef enum FilaBackendSamplerFormat {
    FILA_BACKEND_SAMPLER_FORMAT_INT = 0,
    FILA_BACKEND_SAMPLER_FORMAT_UINT = 1,
    FILA_BACKEND_SAMPLER_FORMAT_FLOAT = 2,
    FILA_BACKEND_SAMPLER_FORMAT_SHADOW = 3,
} FilaBackendSamplerFormat;

typedef enum FilaBackendElementType {
    FILA_BACKEND_ELEMENT_TYPE_BYTE = 0,
    FILA_BACKEND_ELEMENT_TYPE_BYTE2 = 1,
    FILA_BACKEND_ELEMENT_TYPE_BYTE3 = 2,
    FILA_BACKEND_ELEMENT_TYPE_BYTE4 = 3,
    FILA_BACKEND_ELEMENT_TYPE_UBYTE = 4,
    FILA_BACKEND_ELEMENT_TYPE_UBYTE2 = 5,
    FILA_BACKEND_ELEMENT_TYPE_UBYTE3 = 6,
    FILA_BACKEND_ELEMENT_TYPE_UBYTE4 = 7,
    FILA_BACKEND_ELEMENT_TYPE_SHORT = 8,
    FILA_BACKEND_ELEMENT_TYPE_SHORT2 = 9,
    FILA_BACKEND_ELEMENT_TYPE_SHORT3 = 10,
    FILA_BACKEND_ELEMENT_TYPE_SHORT4 = 11,
    FILA_BACKEND_ELEMENT_TYPE_USHORT = 12,
    FILA_BACKEND_ELEMENT_TYPE_USHORT2 = 13,
    FILA_BACKEND_ELEMENT_TYPE_USHORT3 = 14,
    FILA_BACKEND_ELEMENT_TYPE_USHORT4 = 15,
    FILA_BACKEND_ELEMENT_TYPE_INT = 16,
    FILA_BACKEND_ELEMENT_TYPE_UINT = 17,
    FILA_BACKEND_ELEMENT_TYPE_FLOAT = 18,
    FILA_BACKEND_ELEMENT_TYPE_FLOAT2 = 19,
    FILA_BACKEND_ELEMENT_TYPE_FLOAT3 = 20,
    FILA_BACKEND_ELEMENT_TYPE_FLOAT4 = 21,
    FILA_BACKEND_ELEMENT_TYPE_HALF = 22,
    FILA_BACKEND_ELEMENT_TYPE_HALF2 = 23,
    FILA_BACKEND_ELEMENT_TYPE_HALF3 = 24,
    FILA_BACKEND_ELEMENT_TYPE_HALF4 = 25,
} FilaBackendElementType;

typedef enum FilaBackendCullingMode {
    FILA_BACKEND_CULLING_MODE_NONE = 0,
    FILA_BACKEND_CULLING_MODE_FRONT = 1,
    FILA_BACKEND_CULLING_MODE_BACK = 2,
    FILA_BACKEND_CULLING_MODE_FRONT_AND_BACK = 3,
} FilaBackendCullingMode;

typedef enum FilaBackendTextureSwizzle {
    FILA_BACKEND_TEXTURE_SWIZZLE_SUBSTITUTE_ZERO = 0,
    FILA_BACKEND_TEXTURE_SWIZZLE_SUBSTITUTE_ONE = 1,
    FILA_BACKEND_TEXTURE_SWIZZLE_CHANNEL_0 = 2,
    FILA_BACKEND_TEXTURE_SWIZZLE_CHANNEL_1 = 3,
    FILA_BACKEND_TEXTURE_SWIZZLE_CHANNEL_2 = 4,
    FILA_BACKEND_TEXTURE_SWIZZLE_CHANNEL_3 = 5,
} FilaBackendTextureSwizzle;

typedef enum FilaBackendBlendEquation {
    FILA_BACKEND_BLEND_EQUATION_ADD = 0,
    FILA_BACKEND_BLEND_EQUATION_SUBTRACT = 1,
    FILA_BACKEND_BLEND_EQUATION_REVERSE_SUBTRACT = 2,
    FILA_BACKEND_BLEND_EQUATION_MIN = 3,
    FILA_BACKEND_BLEND_EQUATION_MAX = 4,
} FilaBackendBlendEquation;

typedef enum FilaBackendBlendFunction {
    FILA_BACKEND_BLEND_FUNCTION_ZERO = 0,
    FILA_BACKEND_BLEND_FUNCTION_ONE = 1,
    FILA_BACKEND_BLEND_FUNCTION_SRC_COLOR = 2,
    FILA_BACKEND_BLEND_FUNCTION_ONE_MINUS_SRC_COLOR = 3,
    FILA_BACKEND_BLEND_FUNCTION_DST_COLOR = 4,
    FILA_BACKEND_BLEND_FUNCTION_ONE_MINUS_DST_COLOR = 5,
    FILA_BACKEND_BLEND_FUNCTION_SRC_ALPHA = 6,
    FILA_BACKEND_BLEND_FUNCTION_ONE_MINUS_SRC_ALPHA = 7,
    FILA_BACKEND_BLEND_FUNCTION_DST_ALPHA = 8,
    FILA_BACKEND_BLEND_FUNCTION_ONE_MINUS_DST_ALPHA = 9,
    FILA_BACKEND_BLEND_FUNCTION_SRC_ALPHA_SATURATE = 10,
} FilaBackendBlendFunction;

typedef enum FilaBackendStencilOperation {
    FILA_BACKEND_STENCIL_OPERATION_KEEP = 0,
    FILA_BACKEND_STENCIL_OPERATION_ZERO = 1,
    FILA_BACKEND_STENCIL_OPERATION_REPLACE = 2,
    FILA_BACKEND_STENCIL_OPERATION_INCR = 3,
    FILA_BACKEND_STENCIL_OPERATION_INCR_WRAP = 4,
    FILA_BACKEND_STENCIL_OPERATION_DECR = 5,
    FILA_BACKEND_STENCIL_OPERATION_DECR_WRAP = 6,
    FILA_BACKEND_STENCIL_OPERATION_INVERT = 7,
} FilaBackendStencilOperation;

typedef enum FilaBackendStencilFace {
    FILA_BACKEND_STENCIL_FACE_FRONT = 0x1,
    FILA_BACKEND_STENCIL_FACE_BACK = 0x2,
    FILA_BACKEND_STENCIL_FACE_FRONT_AND_BACK = 0x3,
} FilaBackendStencilFace;

FilaBackendTargetBufferFlags FilaBackendTargetBufferFlags_at(size_t index);
FilaBackendRenderTargetAttachmentPoint FilaBackendRenderTargetAttachmentPoint_at(size_t index);
bool FilaBackendPrimitiveType_isStrip(FilaBackendPrimitiveType type);
bool FilaBackendShaderStageFlags_hasStage(FilaBackendShaderStageFlags flags, FilaBackendShaderStage stage);

#ifdef __cplusplus
}
#endif

#endif // FILAMENT_C_BACKEND_DRIVERENUMS_H

