#ifndef FILAMENT_C_BACKEND_DRIVERENUMS_H
#define FILAMENT_C_BACKEND_DRIVERENUMS_H

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

#include "Handle.h"

#ifdef __cplusplus
extern "C" {
#endif


typedef enum FilaBackendFeatureLevel {
    FILA_BACKEND_FEATURE_LEVEL_0 = 0,
    FILA_BACKEND_FEATURE_LEVEL_1 = 1,
    FILA_BACKEND_FEATURE_LEVEL_2 = 2,
    FILA_BACKEND_FEATURE_LEVEL_3 = 3,
} FilaBackendFeatureLevel;

typedef enum FilaBackendBackend {
    FILA_BACKEND_DEFAULT = 0,
    FILA_BACKEND_OPENGL = 1,
    FILA_BACKEND_VULKAN = 2,
    FILA_BACKEND_METAL = 3,
    FILA_BACKEND_WEBGPU = 4,
    FILA_BACKEND_NOOP = 5,
} FilaBackendBackend;

typedef enum FilaBackendTimerQueryResult {
    FILA_BACKEND_TIMER_QUERY_ERROR = -1,
    FILA_BACKEND_TIMER_QUERY_NOT_READY = 0,
    FILA_BACKEND_TIMER_QUERY_AVAILABLE = 1,
} FilaBackendTimerQueryResult;

typedef enum FilaBackendShaderLanguage {
    FILA_BACKEND_SHADER_LANGUAGE_UNSPECIFIED = -1,
    FILA_BACKEND_SHADER_LANGUAGE_ESSL1 = 0,
    FILA_BACKEND_SHADER_LANGUAGE_ESSL3 = 1,
    FILA_BACKEND_SHADER_LANGUAGE_SPIRV = 2,
    FILA_BACKEND_SHADER_LANGUAGE_MSL = 3,
    FILA_BACKEND_SHADER_LANGUAGE_METAL_LIBRARY = 4,
    FILA_BACKEND_SHADER_LANGUAGE_WGSL = 5,
} FilaBackendShaderLanguage;

typedef enum FilaBackendShaderStage {
    FILA_BACKEND_SHADER_STAGE_VERTEX = 0,
    FILA_BACKEND_SHADER_STAGE_FRAGMENT = 1,
    FILA_BACKEND_SHADER_STAGE_COMPUTE = 2,
} FilaBackendShaderStage;

typedef enum FilaBackendShaderStageFlags {
    FILA_BACKEND_SHADER_STAGE_FLAGS_NONE = 0,
    FILA_BACKEND_SHADER_STAGE_FLAGS_VERTEX = 0x1,
    FILA_BACKEND_SHADER_STAGE_FLAGS_FRAGMENT = 0x2,
    FILA_BACKEND_SHADER_STAGE_FLAGS_COMPUTE = 0x4,
    FILA_BACKEND_SHADER_STAGE_FLAGS_ALL = 0x7,
} FilaBackendShaderStageFlags;

typedef enum FilaBackendTextureType {
    FILA_BACKEND_TEXTURE_TYPE_FLOAT = 0,
    FILA_BACKEND_TEXTURE_TYPE_INT = 1,
    FILA_BACKEND_TEXTURE_TYPE_UINT = 2,
    FILA_BACKEND_TEXTURE_TYPE_DEPTH = 3,
    FILA_BACKEND_TEXTURE_TYPE_STENCIL = 4,
    FILA_BACKEND_TEXTURE_TYPE_DEPTH_STENCIL = 5,
} FilaBackendTextureType;

typedef enum FilaBackendDescriptorType {
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_FLOAT = 0,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_INT = 1,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_UINT = 2,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_DEPTH = 3,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_ARRAY_FLOAT = 4,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_ARRAY_INT = 5,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_ARRAY_UINT = 6,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_ARRAY_DEPTH = 7,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_CUBE_FLOAT = 8,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_CUBE_INT = 9,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_CUBE_UINT = 10,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_CUBE_DEPTH = 11,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_CUBE_ARRAY_FLOAT = 12,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_CUBE_ARRAY_INT = 13,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_CUBE_ARRAY_UINT = 14,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_CUBE_ARRAY_DEPTH = 15,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_3D_FLOAT = 16,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_3D_INT = 17,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_3D_UINT = 18,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_MS_FLOAT = 19,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_MS_INT = 20,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_MS_UINT = 21,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_MS_ARRAY_FLOAT = 22,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_MS_ARRAY_INT = 23,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_2D_MS_ARRAY_UINT = 24,
    FILA_BACKEND_DESCRIPTOR_TYPE_SAMPLER_EXTERNAL = 25,
    FILA_BACKEND_DESCRIPTOR_TYPE_UNIFORM_BUFFER = 26,
    FILA_BACKEND_DESCRIPTOR_TYPE_SHADER_STORAGE_BUFFER = 27,
    FILA_BACKEND_DESCRIPTOR_TYPE_INPUT_ATTACHMENT = 28,
} FilaBackendDescriptorType;

typedef enum FilaBackendDescriptorFlags {
    FILA_BACKEND_DESCRIPTOR_FLAGS_NONE = 0x00,
    FILA_BACKEND_DESCRIPTOR_FLAGS_DYNAMIC_OFFSET = 0x01,
    FILA_BACKEND_DESCRIPTOR_FLAGS_UNFILTERABLE = 0x02,
} FilaBackendDescriptorFlags;

typedef uint8_t FilaBackendDescriptorSet;
typedef uint8_t FilaBackendDescriptorBinding;

typedef struct FilaBackendDescriptorSetLayoutDescriptorData {
    FilaBackendDescriptorType type;
    FilaBackendShaderStageFlags stageFlags;
    FilaBackendDescriptorBinding binding;
    FilaBackendDescriptorFlags flags;
    uint16_t count;
} FilaBackendDescriptorSetLayoutDescriptorData;

typedef enum FilaBackendTargetBufferFlags {
    FILA_BACKEND_TARGET_BUFFER_NONE = 0x00000000u,
    FILA_BACKEND_TARGET_BUFFER_COLOR0 = 0x00000001u,
    FILA_BACKEND_TARGET_BUFFER_COLOR1 = 0x00000002u,
    FILA_BACKEND_TARGET_BUFFER_COLOR2 = 0x00000004u,
    FILA_BACKEND_TARGET_BUFFER_COLOR3 = 0x00000008u,
    FILA_BACKEND_TARGET_BUFFER_COLOR4 = 0x00000010u,
    FILA_BACKEND_TARGET_BUFFER_COLOR5 = 0x00000020u,
    FILA_BACKEND_TARGET_BUFFER_COLOR6 = 0x00000040u,
    FILA_BACKEND_TARGET_BUFFER_COLOR7 = 0x00000080u,
    FILA_BACKEND_TARGET_BUFFER_COLOR = 0x00000001u,
    FILA_BACKEND_TARGET_BUFFER_COLOR_ALL = 0x000000FFu,
    FILA_BACKEND_TARGET_BUFFER_DEPTH = 0x10000000u,
    FILA_BACKEND_TARGET_BUFFER_STENCIL = 0x20000000u,
    FILA_BACKEND_TARGET_BUFFER_DEPTH_AND_STENCIL = 0x30000000u,
    FILA_BACKEND_TARGET_BUFFER_ALL = 0x300000FFu,
} FilaBackendTargetBufferFlags;

typedef enum FilaBackendTextureCubemapFace {
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_X = 0,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_X = 1,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_Y = 2,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_Y = 3,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_POSITIVE_Z = 4,
    FILA_BACKEND_TEXTURE_CUBEMAP_FACE_NEGATIVE_Z = 5,
} FilaBackendTextureCubemapFace;

typedef enum FilaBackendRenderTargetAttachmentPoint {
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR0 = 0,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR1 = 1,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR2 = 2,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR3 = 3,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR4 = 4,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR5 = 5,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR6 = 6,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR7 = 7,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_DEPTH = 8,
    FILA_BACKEND_RENDER_TARGET_ATTACHMENT_COLOR = 0,
} FilaBackendRenderTargetAttachmentPoint;

typedef enum FilaBackendTextureUsage {
    FILA_BACKEND_TEXTURE_USAGE_NONE = 0x0000,
    FILA_BACKEND_TEXTURE_USAGE_COLOR_ATTACHMENT = 0x0001,
    FILA_BACKEND_TEXTURE_USAGE_DEPTH_ATTACHMENT = 0x0002,
    FILA_BACKEND_TEXTURE_USAGE_STENCIL_ATTACHMENT = 0x0004,
    FILA_BACKEND_TEXTURE_USAGE_UPLOADABLE = 0x0008,
    FILA_BACKEND_TEXTURE_USAGE_SAMPLEABLE = 0x0010,
    FILA_BACKEND_TEXTURE_USAGE_SUBPASS_INPUT = 0x0020,
    FILA_BACKEND_TEXTURE_USAGE_BLIT_SRC = 0x0040,
    FILA_BACKEND_TEXTURE_USAGE_BLIT_DST = 0x0080,
    FILA_BACKEND_TEXTURE_USAGE_PROTECTED = 0x0100,
    FILA_BACKEND_TEXTURE_USAGE_GEN_MIPMAPPABLE = 0x0200,
    FILA_BACKEND_TEXTURE_USAGE_DEFAULT = 0x0018,
    FILA_BACKEND_TEXTURE_USAGE_ALL_ATTACHMENTS = 0x0027,
} FilaBackendTextureUsage;

typedef enum FilaBackendTextureFormat {
    FILA_BACKEND_TEXTURE_FORMAT_R8 = 0,
    FILA_BACKEND_TEXTURE_FORMAT_R8_SNORM = 1,
    FILA_BACKEND_TEXTURE_FORMAT_R8UI = 2,
    FILA_BACKEND_TEXTURE_FORMAT_R8I = 3,
    FILA_BACKEND_TEXTURE_FORMAT_STENCIL8 = 4,
    FILA_BACKEND_TEXTURE_FORMAT_R16F = 5,
    FILA_BACKEND_TEXTURE_FORMAT_R16UI = 6,
    FILA_BACKEND_TEXTURE_FORMAT_R16I = 7,
    FILA_BACKEND_TEXTURE_FORMAT_RG8 = 8,
    FILA_BACKEND_TEXTURE_FORMAT_RG8_SNORM = 9,
    FILA_BACKEND_TEXTURE_FORMAT_RG8UI = 10,
    FILA_BACKEND_TEXTURE_FORMAT_RG8I = 11,
    FILA_BACKEND_TEXTURE_FORMAT_RGB565 = 12,
    FILA_BACKEND_TEXTURE_FORMAT_RGB9_E5 = 13,
    FILA_BACKEND_TEXTURE_FORMAT_RGB5_A1 = 14,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA4 = 15,
    FILA_BACKEND_TEXTURE_FORMAT_DEPTH16 = 16,
    FILA_BACKEND_TEXTURE_FORMAT_RGB8 = 17,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8 = 18,
    FILA_BACKEND_TEXTURE_FORMAT_RGB8_SNORM = 19,
    FILA_BACKEND_TEXTURE_FORMAT_RGB8UI = 20,
    FILA_BACKEND_TEXTURE_FORMAT_RGB8I = 21,
    FILA_BACKEND_TEXTURE_FORMAT_DEPTH24 = 22,
    FILA_BACKEND_TEXTURE_FORMAT_R32F = 23,
    FILA_BACKEND_TEXTURE_FORMAT_R32UI = 24,
    FILA_BACKEND_TEXTURE_FORMAT_R32I = 25,
    FILA_BACKEND_TEXTURE_FORMAT_RG16F = 26,
    FILA_BACKEND_TEXTURE_FORMAT_RG16UI = 27,
    FILA_BACKEND_TEXTURE_FORMAT_RG16I = 28,
    FILA_BACKEND_TEXTURE_FORMAT_R11F_G11F_B10F = 29,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA8 = 30,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_A8 = 31,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA8_SNORM = 32,
    FILA_BACKEND_TEXTURE_FORMAT_UNUSED = 33,
    FILA_BACKEND_TEXTURE_FORMAT_RGB10_A2 = 34,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA8UI = 35,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA8I = 36,
    FILA_BACKEND_TEXTURE_FORMAT_DEPTH32F = 37,
    FILA_BACKEND_TEXTURE_FORMAT_DEPTH24_STENCIL8 = 38,
    FILA_BACKEND_TEXTURE_FORMAT_DEPTH32F_STENCIL8 = 39,
    FILA_BACKEND_TEXTURE_FORMAT_RGB16F = 40,
    FILA_BACKEND_TEXTURE_FORMAT_RGB16UI = 41,
    FILA_BACKEND_TEXTURE_FORMAT_RGB16I = 42,
    FILA_BACKEND_TEXTURE_FORMAT_RG32F = 43,
    FILA_BACKEND_TEXTURE_FORMAT_RG32UI = 44,
    FILA_BACKEND_TEXTURE_FORMAT_RG32I = 45,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA16F = 46,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA16UI = 47,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA16I = 48,
    FILA_BACKEND_TEXTURE_FORMAT_RGB32F = 49,
    FILA_BACKEND_TEXTURE_FORMAT_RGB32UI = 50,
    FILA_BACKEND_TEXTURE_FORMAT_RGB32I = 51,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA32F = 52,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA32UI = 53,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA32I = 54,
    FILA_BACKEND_TEXTURE_FORMAT_EAC_R11 = 55,
    FILA_BACKEND_TEXTURE_FORMAT_EAC_R11_SIGNED = 56,
    FILA_BACKEND_TEXTURE_FORMAT_EAC_RG11 = 57,
    FILA_BACKEND_TEXTURE_FORMAT_EAC_RG11_SIGNED = 58,
    FILA_BACKEND_TEXTURE_FORMAT_ETC2_RGB8 = 59,
    FILA_BACKEND_TEXTURE_FORMAT_ETC2_SRGB8 = 60,
    FILA_BACKEND_TEXTURE_FORMAT_ETC2_RGB8_A1 = 61,
    FILA_BACKEND_TEXTURE_FORMAT_ETC2_SRGB8_A1 = 62,
    FILA_BACKEND_TEXTURE_FORMAT_ETC2_EAC_RGBA8 = 63,
    FILA_BACKEND_TEXTURE_FORMAT_ETC2_EAC_SRGBA8 = 64,
    FILA_BACKEND_TEXTURE_FORMAT_DXT1_RGB = 65,
    FILA_BACKEND_TEXTURE_FORMAT_DXT1_RGBA = 66,
    FILA_BACKEND_TEXTURE_FORMAT_DXT3_RGBA = 67,
    FILA_BACKEND_TEXTURE_FORMAT_DXT5_RGBA = 68,
    FILA_BACKEND_TEXTURE_FORMAT_DXT1_SRGB = 69,
    FILA_BACKEND_TEXTURE_FORMAT_DXT1_SRGBA = 70,
    FILA_BACKEND_TEXTURE_FORMAT_DXT3_SRGBA = 71,
    FILA_BACKEND_TEXTURE_FORMAT_DXT5_SRGBA = 72,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_4x4 = 73,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_5x4 = 74,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_5x5 = 75,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_6x5 = 76,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_6x6 = 77,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_8x5 = 78,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_8x6 = 79,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_8x8 = 80,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_10x5 = 81,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_10x6 = 82,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_10x8 = 83,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_10x10 = 84,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_12x10 = 85,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_ASTC_12x12 = 86,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_4x4 = 87,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_5x4 = 88,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_5x5 = 89,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_6x5 = 90,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_6x6 = 91,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_8x5 = 92,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_8x6 = 93,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_8x8 = 94,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_10x5 = 95,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_10x6 = 96,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_10x8 = 97,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_10x10 = 98,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_12x10 = 99,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB8_ALPHA8_ASTC_12x12 = 100,
    FILA_BACKEND_TEXTURE_FORMAT_RED_RGTC1 = 101,
    FILA_BACKEND_TEXTURE_FORMAT_SIGNED_RED_RGTC1 = 102,
    FILA_BACKEND_TEXTURE_FORMAT_RED_GREEN_RGTC2 = 103,
    FILA_BACKEND_TEXTURE_FORMAT_SIGNED_RED_GREEN_RGTC2 = 104,
    FILA_BACKEND_TEXTURE_FORMAT_RGB_BPTC_SIGNED_FLOAT = 105,
    FILA_BACKEND_TEXTURE_FORMAT_RGB_BPTC_UNSIGNED_FLOAT = 106,
    FILA_BACKEND_TEXTURE_FORMAT_RGBA_BPTC_UNORM = 107,
    FILA_BACKEND_TEXTURE_FORMAT_SRGB_ALPHA_BPTC_UNORM = 108,
} FilaBackendTextureFormat;

typedef enum FilaBackendBufferUsage {
    FILA_BACKEND_BUFFER_USAGE_STATIC = 0,
    FILA_BACKEND_BUFFER_USAGE_DYNAMIC = 1,
    FILA_BACKEND_BUFFER_USAGE_DYNAMIC_BIT = 0x1,
    FILA_BACKEND_BUFFER_USAGE_SHARED_WRITE_BIT = 0x04,
} FilaBackendBufferUsage;

typedef enum FilaBackendMapBufferAccessFlags {
    FILA_BACKEND_MAP_BUFFER_ACCESS_WRITE_BIT = 0x2,
    FILA_BACKEND_MAP_BUFFER_ACCESS_INVALIDATE_RANGE_BIT = 0x4,
} FilaBackendMapBufferAccessFlags;

typedef enum FilaBackendFenceStatus {
    FILA_BACKEND_FENCE_STATUS_ERROR = -1,
    FILA_BACKEND_FENCE_STATUS_CONDITION_SATISFIED = 0,
    FILA_BACKEND_FENCE_STATUS_TIMEOUT_EXPIRED = 1,
} FilaBackendFenceStatus;

typedef enum FilaBackendShaderModel {
    FILA_BACKEND_SHADER_MODEL_MOBILE = 1,
    FILA_BACKEND_SHADER_MODEL_DESKTOP = 2,
} FilaBackendShaderModel;

typedef enum FilaBackendPrimitiveType {
    FILA_BACKEND_PRIMITIVE_TYPE_POINTS = 0,
    FILA_BACKEND_PRIMITIVE_TYPE_LINES = 1,
    FILA_BACKEND_PRIMITIVE_TYPE_LINE_STRIP = 3,
    FILA_BACKEND_PRIMITIVE_TYPE_TRIANGLES = 4,
    FILA_BACKEND_PRIMITIVE_TYPE_TRIANGLE_STRIP = 5,
} FilaBackendPrimitiveType;

typedef enum FilaBackendUniformType {
    FILA_BACKEND_UNIFORM_TYPE_BOOL = 0,
    FILA_BACKEND_UNIFORM_TYPE_BOOL2 = 1,
    FILA_BACKEND_UNIFORM_TYPE_BOOL3 = 2,
    FILA_BACKEND_UNIFORM_TYPE_BOOL4 = 3,
    FILA_BACKEND_UNIFORM_TYPE_FLOAT = 4,
    FILA_BACKEND_UNIFORM_TYPE_FLOAT2 = 5,
    FILA_BACKEND_UNIFORM_TYPE_FLOAT3 = 6,
    FILA_BACKEND_UNIFORM_TYPE_FLOAT4 = 7,
    FILA_BACKEND_UNIFORM_TYPE_INT = 8,
    FILA_BACKEND_UNIFORM_TYPE_INT2 = 9,
    FILA_BACKEND_UNIFORM_TYPE_INT3 = 10,
    FILA_BACKEND_UNIFORM_TYPE_INT4 = 11,
    FILA_BACKEND_UNIFORM_TYPE_UINT = 12,
    FILA_BACKEND_UNIFORM_TYPE_UINT2 = 13,
    FILA_BACKEND_UNIFORM_TYPE_UINT3 = 14,
    FILA_BACKEND_UNIFORM_TYPE_UINT4 = 15,
    FILA_BACKEND_UNIFORM_TYPE_MAT3 = 16,
    FILA_BACKEND_UNIFORM_TYPE_MAT4 = 17,
    FILA_BACKEND_UNIFORM_TYPE_STRUCT = 18,
} FilaBackendUniformType;

typedef enum FilaBackendConstantType {
    FILA_BACKEND_CONSTANT_TYPE_INT = 0,
    FILA_BACKEND_CONSTANT_TYPE_FLOAT = 1,
    FILA_BACKEND_CONSTANT_TYPE_BOOL = 2,
} FilaBackendConstantType;

typedef enum FilaBackendPrecision {
    FILA_BACKEND_PRECISION_LOW = 0,
    FILA_BACKEND_PRECISION_MEDIUM = 1,
    FILA_BACKEND_PRECISION_HIGH = 2,
    FILA_BACKEND_PRECISION_DEFAULT = 3,
} FilaBackendPrecision;

typedef enum FilaBackendCompilerPriorityQueue {
    FILA_BACKEND_COMPILER_PRIORITY_QUEUE_CRITICAL = 0,
    FILA_BACKEND_COMPILER_PRIORITY_QUEUE_HIGH = 1,
    FILA_BACKEND_COMPILER_PRIORITY_QUEUE_LOW = 2,
} FilaBackendCompilerPriorityQueue;

typedef enum FilaBackendSamplerType {
    FILA_BACKEND_SAMPLER_TYPE_2D = 0,
    FILA_BACKEND_SAMPLER_TYPE_2D_ARRAY = 1,
    FILA_BACKEND_SAMPLER_TYPE_CUBEMAP = 2,
    FILA_BACKEND_SAMPLER_TYPE_EXTERNAL = 3,
    FILA_BACKEND_SAMPLER_TYPE_3D = 4,
    FILA_BACKEND_SAMPLER_TYPE_CUBEMAP_ARRAY = 5,
} FilaBackendSamplerType;

typedef enum FilaBackendBufferObjectBinding {
    FILA_BACKEND_BUFFER_OBJECT_BINDING_VERTEX = 0,
    FILA_BACKEND_BUFFER_OBJECT_BINDING_UNIFORM = 1,
    FILA_BACKEND_BUFFER_OBJECT_BINDING_SHADER_STORAGE = 2,
} FilaBackendBufferObjectBinding;

typedef enum FilaBackendSamplerFormat {
    FILA_BACKEND_SAMPLER_FORMAT_INT = 0,
    FILA_BACKEND_SAMPLER_FORMAT_UINT = 1,
    FILA_BACKEND_SAMPLER_FORMAT_FLOAT = 2,
    FILA_BACKEND_SAMPLER_FORMAT_SHADOW = 3,
} FilaBackendSamplerFormat;

typedef enum FilaBackendSamplerWrapMode {
    FILA_BACKEND_SAMPLER_WRAP_MODE_CLAMP_TO_EDGE = 0,
    FILA_BACKEND_SAMPLER_WRAP_MODE_REPEAT = 1,
    FILA_BACKEND_SAMPLER_WRAP_MODE_MIRRORED_REPEAT = 2,
} FilaBackendSamplerWrapMode;

typedef enum FilaBackendSamplerMinFilter {
    FILA_BACKEND_SAMPLER_MIN_FILTER_NEAREST = 0,
    FILA_BACKEND_SAMPLER_MIN_FILTER_LINEAR = 1,
    FILA_BACKEND_SAMPLER_MIN_FILTER_NEAREST_MIPMAP_NEAREST = 2,
    FILA_BACKEND_SAMPLER_MIN_FILTER_LINEAR_MIPMAP_NEAREST = 3,
    FILA_BACKEND_SAMPLER_MIN_FILTER_NEAREST_MIPMAP_LINEAR = 4,
    FILA_BACKEND_SAMPLER_MIN_FILTER_LINEAR_MIPMAP_LINEAR = 5,
} FilaBackendSamplerMinFilter;

typedef enum FilaBackendSamplerMagFilter {
    FILA_BACKEND_SAMPLER_MAG_FILTER_NEAREST = 0,
    FILA_BACKEND_SAMPLER_MAG_FILTER_LINEAR = 1,
} FilaBackendSamplerMagFilter;

typedef enum FilaBackendSamplerCompareMode {
    FILA_BACKEND_SAMPLER_COMPARE_MODE_NONE = 0,
    FILA_BACKEND_SAMPLER_COMPARE_MODE_COMPARE_TO_TEXTURE = 1,
} FilaBackendSamplerCompareMode;

typedef enum FilaBackendSamplerCompareFunc {
    FILA_BACKEND_SAMPLER_COMPARE_FUNC_LE = 0,
    FILA_BACKEND_SAMPLER_COMPARE_FUNC_GE = 1,
    FILA_BACKEND_SAMPLER_COMPARE_FUNC_L = 2,
    FILA_BACKEND_SAMPLER_COMPARE_FUNC_G = 3,
    FILA_BACKEND_SAMPLER_COMPARE_FUNC_E = 4,
    FILA_BACKEND_SAMPLER_COMPARE_FUNC_NE = 5,
    FILA_BACKEND_SAMPLER_COMPARE_FUNC_A = 6,
    FILA_BACKEND_SAMPLER_COMPARE_FUNC_N = 7,
} FilaBackendSamplerCompareFunc;

typedef enum FilaBackendElementType {
    FILA_BACKEND_ELEMENT_TYPE_BYTE = 0,
    FILA_BACKEND_ELEMENT_TYPE_BYTE2 = 1,
    FILA_BACKEND_ELEMENT_TYPE_BYTE3 = 2,
    FILA_BACKEND_ELEMENT_TYPE_BYTE4 = 3,
    FILA_BACKEND_ELEMENT_TYPE_UBYTE = 4,
    FILA_BACKEND_ELEMENT_TYPE_UBYTE2 = 5,
    FILA_BACKEND_ELEMENT_TYPE_UBYTE3 = 6,
    FILA_BACKEND_ELEMENT_TYPE_UBYTE4 = 7,
    FILA_BACKEND_ELEMENT_TYPE_SHORT = 8,
    FILA_BACKEND_ELEMENT_TYPE_SHORT2 = 9,
    FILA_BACKEND_ELEMENT_TYPE_SHORT3 = 10,
    FILA_BACKEND_ELEMENT_TYPE_SHORT4 = 11,
    FILA_BACKEND_ELEMENT_TYPE_USHORT = 12,
    FILA_BACKEND_ELEMENT_TYPE_USHORT2 = 13,
    FILA_BACKEND_ELEMENT_TYPE_USHORT3 = 14,
    FILA_BACKEND_ELEMENT_TYPE_USHORT4 = 15,
    FILA_BACKEND_ELEMENT_TYPE_INT = 16,
    FILA_BACKEND_ELEMENT_TYPE_UINT = 17,
    FILA_BACKEND_ELEMENT_TYPE_FLOAT = 18,
    FILA_BACKEND_ELEMENT_TYPE_FLOAT2 = 19,
    FILA_BACKEND_ELEMENT_TYPE_FLOAT3 = 20,
    FILA_BACKEND_ELEMENT_TYPE_FLOAT4 = 21,
    FILA_BACKEND_ELEMENT_TYPE_HALF = 22,
    FILA_BACKEND_ELEMENT_TYPE_HALF2 = 23,
    FILA_BACKEND_ELEMENT_TYPE_HALF3 = 24,
    FILA_BACKEND_ELEMENT_TYPE_HALF4 = 25,
} FilaBackendElementType;

typedef enum FilaBackendCullingMode {
    FILA_BACKEND_CULLING_MODE_NONE = 0,
    FILA_BACKEND_CULLING_MODE_FRONT = 1,
    FILA_BACKEND_CULLING_MODE_BACK = 2,
    FILA_BACKEND_CULLING_MODE_FRONT_AND_BACK = 3,
} FilaBackendCullingMode;

typedef enum FilaBackendTextureSwizzle {
    FILA_BACKEND_TEXTURE_SWIZZLE_SUBSTITUTE_ZERO = 0,
    FILA_BACKEND_TEXTURE_SWIZZLE_SUBSTITUTE_ONE = 1,
    FILA_BACKEND_TEXTURE_SWIZZLE_CHANNEL_0 = 2,
    FILA_BACKEND_TEXTURE_SWIZZLE_CHANNEL_1 = 3,
    FILA_BACKEND_TEXTURE_SWIZZLE_CHANNEL_2 = 4,
    FILA_BACKEND_TEXTURE_SWIZZLE_CHANNEL_3 = 5,
} FilaBackendTextureSwizzle;

typedef enum FilaBackendBlendEquation {
    FILA_BACKEND_BLEND_EQUATION_ADD = 0,
    FILA_BACKEND_BLEND_EQUATION_SUBTRACT = 1,
    FILA_BACKEND_BLEND_EQUATION_REVERSE_SUBTRACT = 2,
    FILA_BACKEND_BLEND_EQUATION_MIN = 3,
    FILA_BACKEND_BLEND_EQUATION_MAX = 4,
} FilaBackendBlendEquation;

typedef enum FilaBackendBlendFunction {
    FILA_BACKEND_BLEND_FUNCTION_ZERO = 0,
    FILA_BACKEND_BLEND_FUNCTION_ONE = 1,
    FILA_BACKEND_BLEND_FUNCTION_SRC_COLOR = 2,
    FILA_BACKEND_BLEND_FUNCTION_ONE_MINUS_SRC_COLOR = 3,
    FILA_BACKEND_BLEND_FUNCTION_DST_COLOR = 4,
    FILA_BACKEND_BLEND_FUNCTION_ONE_MINUS_DST_COLOR = 5,
    FILA_BACKEND_BLEND_FUNCTION_SRC_ALPHA = 6,
    FILA_BACKEND_BLEND_FUNCTION_ONE_MINUS_SRC_ALPHA = 7,
    FILA_BACKEND_BLEND_FUNCTION_DST_ALPHA = 8,
    FILA_BACKEND_BLEND_FUNCTION_ONE_MINUS_DST_ALPHA = 9,
    FILA_BACKEND_BLEND_FUNCTION_SRC_ALPHA_SATURATE = 10,
} FilaBackendBlendFunction;

typedef enum FilaBackendStencilOperation {
    FILA_BACKEND_STENCIL_OPERATION_KEEP = 0,
    FILA_BACKEND_STENCIL_OPERATION_ZERO = 1,
    FILA_BACKEND_STENCIL_OPERATION_REPLACE = 2,
    FILA_BACKEND_STENCIL_OPERATION_INCR = 3,
    FILA_BACKEND_STENCIL_OPERATION_INCR_WRAP = 4,
    FILA_BACKEND_STENCIL_OPERATION_DECR = 5,
    FILA_BACKEND_STENCIL_OPERATION_DECR_WRAP = 6,
    FILA_BACKEND_STENCIL_OPERATION_INVERT = 7,
} FilaBackendStencilOperation;

typedef enum FilaBackendStencilFace {
    FILA_BACKEND_STENCIL_FACE_FRONT = 0x1,
    FILA_BACKEND_STENCIL_FACE_BACK = 0x2,
    FILA_BACKEND_STENCIL_FACE_FRONT_AND_BACK = 0x3,
} FilaBackendStencilFace;

typedef enum FilaBackendStreamType {
    FILA_BACKEND_STREAM_TYPE_NATIVE = 0,
    FILA_BACKEND_STREAM_TYPE_ACQUIRED = 1,
} FilaBackendStreamType;

typedef void (*FilaBackendStreamCallback)(void* image, void* userData);

FilaBackendTargetBufferFlags FilaBackendTargetBufferFlags_at(size_t index);
FilaBackendRenderTargetAttachmentPoint FilaBackendRenderTargetAttachmentPoint_at(size_t index);
bool FilaBackendPrimitiveType_isStrip(FilaBackendPrimitiveType type);
bool FilaBackendShaderStageFlags_hasStage(FilaBackendShaderStageFlags flags, FilaBackendShaderStage stage);
const char* FilaBackendTextureType_toString(FilaBackendTextureType type);
const char* FilaBackendBufferObjectBinding_toString(FilaBackendBufferObjectBinding binding);

FilaBackendTextureType FilaBackendTextureFormat_getTextureType(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isDepth(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isStencil(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isColor(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isUnsignedInt(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isSignedInt(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isCompressed(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isETC2Compression(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isS3TCCompression(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isS3TCSRGBCompression(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isRGTCCompression(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isBPTCCompression(FilaBackendTextureFormat format);
bool FilaBackendTextureFormat_isASTCCompression(FilaBackendTextureFormat format);

size_t FilaBackendPipelineStageCount(void);
size_t FilaBackendShaderModelCount(void);

bool FilaBackendDescriptorType_isDepth(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_isFloat(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_isInt(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_isUnsignedInt(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_is3dType(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_is2dType(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_is2dArrayType(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_isCubeType(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_isCubeArrayType(FilaBackendDescriptorType type);
bool FilaBackendDescriptorType_isMultiSampledType(FilaBackendDescriptorType type);
const char* FilaBackendDescriptorType_toString(FilaBackendDescriptorType type);

bool FilaBackendDescriptorSetLayoutDescriptor_isSamplerType(FilaBackendDescriptorType type);
bool FilaBackendDescriptorSetLayoutDescriptor_isBufferType(FilaBackendDescriptorType type);
bool FilaBackendDescriptorFlags_has(FilaBackendDescriptorFlags flags, FilaBackendDescriptorFlags bit);

#ifdef __cplusplus
}
#endif

#endif // FILAMENT_C_BACKEND_DRIVERENUMS_H

