#ifndef FILAMENT_C_BACKEND_SAMPLERDESCRIPTOR_H
#define FILAMENT_C_BACKEND_SAMPLERDESCRIPTOR_H

#include <stdbool.h>
#include <stdint.h>

#include "DriverEnums.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FilaSamplerDescriptor FilaSamplerDescriptor;


// Compatibility constants for existing sampler descriptor callsites.
#define FILA_BACKEND_SAMPLER_WRAP_CLAMP_TO_EDGE FILA_BACKEND_SAMPLER_WRAP_MODE_CLAMP_TO_EDGE
#define FILA_BACKEND_SAMPLER_WRAP_REPEAT FILA_BACKEND_SAMPLER_WRAP_MODE_REPEAT
#define FILA_BACKEND_SAMPLER_WRAP_MIRRORED_REPEAT FILA_BACKEND_SAMPLER_WRAP_MODE_MIRRORED_REPEAT

#define FILA_BACKEND_SAMPLER_MIN_NEAREST FILA_BACKEND_SAMPLER_MIN_FILTER_NEAREST
#define FILA_BACKEND_SAMPLER_MIN_LINEAR FILA_BACKEND_SAMPLER_MIN_FILTER_LINEAR
#define FILA_BACKEND_SAMPLER_MIN_NEAREST_MIPMAP_NEAREST FILA_BACKEND_SAMPLER_MIN_FILTER_NEAREST_MIPMAP_NEAREST
#define FILA_BACKEND_SAMPLER_MIN_LINEAR_MIPMAP_NEAREST FILA_BACKEND_SAMPLER_MIN_FILTER_LINEAR_MIPMAP_NEAREST
#define FILA_BACKEND_SAMPLER_MIN_NEAREST_MIPMAP_LINEAR FILA_BACKEND_SAMPLER_MIN_FILTER_NEAREST_MIPMAP_LINEAR
#define FILA_BACKEND_SAMPLER_MIN_LINEAR_MIPMAP_LINEAR FILA_BACKEND_SAMPLER_MIN_FILTER_LINEAR_MIPMAP_LINEAR

#define FILA_BACKEND_SAMPLER_MAG_NEAREST FILA_BACKEND_SAMPLER_MAG_FILTER_NEAREST
#define FILA_BACKEND_SAMPLER_MAG_LINEAR FILA_BACKEND_SAMPLER_MAG_FILTER_LINEAR

#define FILA_BACKEND_SAMPLER_COMPARE_NONE FILA_BACKEND_SAMPLER_COMPARE_MODE_NONE
#define FILA_BACKEND_SAMPLER_COMPARE_TO_TEXTURE FILA_BACKEND_SAMPLER_COMPARE_MODE_COMPARE_TO_TEXTURE

#define FILA_BACKEND_SAMPLER_COMPARE_LE FILA_BACKEND_SAMPLER_COMPARE_FUNC_LE
#define FILA_BACKEND_SAMPLER_COMPARE_GE FILA_BACKEND_SAMPLER_COMPARE_FUNC_GE
#define FILA_BACKEND_SAMPLER_COMPARE_L FILA_BACKEND_SAMPLER_COMPARE_FUNC_L
#define FILA_BACKEND_SAMPLER_COMPARE_G FILA_BACKEND_SAMPLER_COMPARE_FUNC_G
#define FILA_BACKEND_SAMPLER_COMPARE_E FILA_BACKEND_SAMPLER_COMPARE_FUNC_E
#define FILA_BACKEND_SAMPLER_COMPARE_NE FILA_BACKEND_SAMPLER_COMPARE_FUNC_NE
#define FILA_BACKEND_SAMPLER_COMPARE_A FILA_BACKEND_SAMPLER_COMPARE_FUNC_A
#define FILA_BACKEND_SAMPLER_COMPARE_N FILA_BACKEND_SAMPLER_COMPARE_FUNC_N

typedef struct FilaBackendSamplerParams {
    FilaBackendSamplerMagFilter filterMag;
    FilaBackendSamplerMinFilter filterMin;
    FilaBackendSamplerWrapMode wrapS;
    FilaBackendSamplerWrapMode wrapT;
    FilaBackendSamplerWrapMode wrapR;
    uint8_t anisotropyLog2;
    FilaBackendSamplerCompareMode compareMode;
    FilaBackendSamplerCompareFunc compareFunc;
} FilaBackendSamplerParams;

FilaSamplerDescriptor* FilaSamplerDescriptor_create(void);
void FilaSamplerDescriptor_destroy(FilaSamplerDescriptor* desc);

void FilaSamplerDescriptor_setTextureHandleId(FilaSamplerDescriptor* desc, uint32_t handleId);
uint32_t FilaSamplerDescriptor_getTextureHandleId(const FilaSamplerDescriptor* desc);
bool FilaSamplerDescriptor_hasTextureHandle(const FilaSamplerDescriptor* desc);
void FilaSamplerDescriptor_clearTextureHandle(FilaSamplerDescriptor* desc);

void FilaSamplerParams_setDefaults(FilaBackendSamplerParams* params);
bool FilaSamplerParams_isFiltered(const FilaBackendSamplerParams* params);

void FilaSamplerDescriptor_setParams(FilaSamplerDescriptor* desc, const FilaBackendSamplerParams* params);
bool FilaSamplerDescriptor_getParams(const FilaSamplerDescriptor* desc, FilaBackendSamplerParams* outParams);
bool FilaSamplerDescriptor_isFiltered(const FilaSamplerDescriptor* desc);

#ifdef __cplusplus
}
#endif

#endif // FILAMENT_C_BACKEND_SAMPLERDESCRIPTOR_H

