package buildlogic.apigen.kotlin

import buildlogic.apigen.c.CFunction

/**
 * Writes the common `@ExternalSymbolName external fun` of a C header's functions, named like the C symbol (web binds
 * by global name), with the types externals take: any pointer is a `NativePointer`, 32-bit integers and enums an
 * `Int`, 64-bit ones a `Long`.
 */
internal object KotlinExternalsWriter {
    /** The Kotlin file binding [functions] (of the header `c/[source]`) in [pkg]; [interop]: the package declaring the two names. */
    fun write(source: String, functions: List<CFunction>, pkg: String, interop: String) =
        "// Generated by generateKotlinExternals from c/$source; do not edit.\n" +
            "package $pkg\n\nimport $interop.ExternalSymbolName\n" +
            (if (functions.any { f -> f.returns == "ptr" || f.params.any { it.second == "ptr" } }) "import $interop.NativePointer\n" else "") +
            functions.joinToString("") { "\n${external(it)}" }

    private fun external(f: CFunction): String {
        val params = f.params.joinToString { (name, abi) -> "${if (name in KEYWORDS) "`$name`" else name}: ${TYPES.getValue(abi)}" }
        val result = if (f.returns == "void") "" else ": ${TYPES.getValue(f.returns)}"
        return "@ExternalSymbolName(\"${f.name}\")\ninternal external fun ${f.name}($params)$result\n"
    }

    private val TYPES = mapOf("ptr" to "NativePointer", "i32" to "Int", "i64" to "Long", "f32" to "Float", "f64" to "Double", "bool" to "Boolean")
    private val KEYWORDS = setOf(
        "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface", "is", "null",
        "object", "package", "return", "super", "this", "throw", "true", "try", "typealias", "typeof", "val", "var",
        "when", "while",
    )
}
