// Generated by generateKotlinExternals from c/filamat/manual/FilaFilamatMaterialBuilderManual.h; do not edit.
package io.github.erkko68.filament.filamat.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_build")
internal external fun FilaFilamatMaterialBuilder_build(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_constant_int")
internal external fun FilaFilamatMaterialBuilder_constant_int(self: NativePointer, name: NativePointer, type: Int, defaultValue: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_constant_float")
internal external fun FilaFilamatMaterialBuilder_constant_float(self: NativePointer, name: NativePointer, type: Int, defaultValue: Float): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_constant_bool")
internal external fun FilaFilamatMaterialBuilder_constant_bool(self: NativePointer, name: NativePointer, type: Int, defaultValue: Boolean): NativePointer
