// Generated by generateKotlinExternals from c/filament/generated/FilaACESLegacyToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaACESLegacyToneMapper_create")
internal external fun FilaACESLegacyToneMapper_create(): NativePointer

@ExternalSymbolName("FilaACESLegacyToneMapper_destroy")
internal external fun FilaACESLegacyToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaACESLegacyToneMapper_asToneMapper")
internal external fun FilaACESLegacyToneMapper_asToneMapper(self: NativePointer): NativePointer

@ExternalSymbolName("FilaACESLegacyToneMapper_invoke")
internal external fun FilaACESLegacyToneMapper_invoke(self: NativePointer, c: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaACESLegacyToneMapper_isOneDimensional")
internal external fun FilaACESLegacyToneMapper_isOneDimensional(self: NativePointer): Boolean

@ExternalSymbolName("FilaACESLegacyToneMapper_isLDR")
internal external fun FilaACESLegacyToneMapper_isLDR(self: NativePointer): Boolean
