// Generated by generateKotlinExternals from c/filament/generated/FilaFilmicToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFilmicToneMapper_create")
internal external fun FilaFilmicToneMapper_create(): NativePointer

@ExternalSymbolName("FilaFilmicToneMapper_destroy")
internal external fun FilaFilmicToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaFilmicToneMapper_asToneMapper")
internal external fun FilaFilmicToneMapper_asToneMapper(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilmicToneMapper_invoke")
internal external fun FilaFilmicToneMapper_invoke(self: NativePointer, x: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFilmicToneMapper_isOneDimensional")
internal external fun FilaFilmicToneMapper_isOneDimensional(self: NativePointer): Boolean

@ExternalSymbolName("FilaFilmicToneMapper_isLDR")
internal external fun FilaFilmicToneMapper_isLDR(self: NativePointer): Boolean
