// Generated by generateKotlinExternals from c/filament/generated/FilaPBRNeutralToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaPBRNeutralToneMapper_create")
internal external fun FilaPBRNeutralToneMapper_create(): NativePointer

@ExternalSymbolName("FilaPBRNeutralToneMapper_destroy")
internal external fun FilaPBRNeutralToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaPBRNeutralToneMapper_asToneMapper")
internal external fun FilaPBRNeutralToneMapper_asToneMapper(self: NativePointer): NativePointer

@ExternalSymbolName("FilaPBRNeutralToneMapper_invoke")
internal external fun FilaPBRNeutralToneMapper_invoke(self: NativePointer, color: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaPBRNeutralToneMapper_isOneDimensional")
internal external fun FilaPBRNeutralToneMapper_isOneDimensional(self: NativePointer): Boolean

@ExternalSymbolName("FilaPBRNeutralToneMapper_isLDR")
internal external fun FilaPBRNeutralToneMapper_isLDR(self: NativePointer): Boolean
