// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioAssetConfigurationExtended.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioAssetConfigurationExtended_create")
internal external fun FilaGltfioAssetConfigurationExtended_create(): NativePointer

@ExternalSymbolName("FilaGltfioAssetConfigurationExtended_destroy")
internal external fun FilaGltfioAssetConfigurationExtended_destroy(self: NativePointer)

@ExternalSymbolName("FilaGltfioAssetConfigurationExtended_isSupported")
internal external fun FilaGltfioAssetConfigurationExtended_isSupported(): Boolean

@ExternalSymbolName("FilaGltfioAssetConfigurationExtended_getGltfPath")
internal external fun FilaGltfioAssetConfigurationExtended_getGltfPath(self: NativePointer): NativePointer
