import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Writes the JNI forwarders behind the common `external fun`s (skiko-style bindings).
 *
 * Every `@ExternalSymbolName("FilaX") external fun` in [sources] is a JNI method on its file's
 * facade class; this emits the `Java_…` C function that calls the C symbol, one `.c` per Kotlin
 * file into [outputDir]. Only the Kotlin types are known: pointers go through `void*`, which C
 * converts to the declared pointer type, and the Fila* prototypes let the C compiler check the rest.
 */
@CacheableTask
abstract class GenerateJniGlue : DefaultTask() {
    @get:InputFiles @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val sources: ConfigurableFileCollection

    /** Fila* headers to include, for the prototypes. */
    @get:InputFiles @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val headers: ConfigurableFileCollection

    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val out = outputDir.get().asFile.apply { deleteRecursively(); mkdirs() }
        val includes = headers.files.map { it.name }.sorted().joinToString("") { "#include \"$it\"\n" }
        sources.files.sortedBy { it.path }.forEach { file ->
            val text = file.readText()
            val decls = DECL.findAll(text).toList()
            if (decls.isEmpty()) return@forEach
            val pkg = Regex("""^package\s+([\w.]+)""", RegexOption.MULTILINE).find(text)?.groupValues?.get(1).orEmpty()
            val facade = Regex("""@file:JvmName\("(\w+)"\)""").find(text)?.groupValues?.get(1)
                ?: (file.nameWithoutExtension.replaceFirstChar { it.uppercase() } + "Kt")
            val jniClass = mangle(if (pkg.isEmpty()) facade else "$pkg.$facade")
            val c = StringBuilder("// Generated by GenerateJniGlue from ${file.name}. Do not edit.\n")
            c.append("#include <jni.h>\n#include <stdint.h>\n\n").append(includes).append("\n")
            decls.forEach { m ->
                val (symbol, name, params, ret) = m.destructured
                c.append(forwarder(jniClass, symbol, name, parseParams(params, "$name in ${file.name}"), ret.ifEmpty { "Unit" }, "$name in ${file.name}"))
            }
            File(out, "${file.nameWithoutExtension}.c").writeText(c.toString())
        }
    }

    private class Param(val name: String, val type: String)

    private fun parseParams(params: String, where: String): List<Param> =
        params.split(',').map { it.trim() }.filter { it.isNotEmpty() }.map {
            val (n, t) = it.split(':').map(String::trim).also { p -> check(p.size == 2) { "Can't parse parameter '$it' of $where" } }
            Param(n.removeSurrounding("`"), t)
        }

    private fun forwarder(jniClass: String, symbol: String, name: String, params: List<Param>, ret: String, where: String): String {
        val jniParams = params.joinToString("") { ", ${jniType(it.type, where)} ${it.name}" }
        val args = params.joinToString { if (it.type == "NativePointer") "(void*)(intptr_t) ${it.name}" else it.name }
        val call = "$symbol($args)"
        val body = when (ret) {
            "Unit" -> "$call;"
            "NativePointer" -> "return (jlong)(intptr_t) $call;"
            "Boolean" -> "return $call ? JNI_TRUE : JNI_FALSE;"
            else -> "return (${jniType(ret, where)}) $call;"
        }
        val jniRet = if (ret == "Unit") "void" else jniType(ret, where)
        return "JNIEXPORT $jniRet JNICALL Java_${jniClass}_${mangle(name)}(JNIEnv* env, jclass cls$jniParams) {\n    $body\n}\n\n"
    }

    private fun jniType(kotlin: String, where: String) = when (kotlin) {
        "NativePointer", "Long" -> "jlong"
        "Int" -> "jint"
        "Float" -> "jfloat"
        "Double" -> "jdouble"
        "Boolean" -> "jboolean"
        else -> error("GenerateJniGlue: no JNI mapping for Kotlin type '$kotlin' ($where)")
    }

    // JNI name mangling: '_' → "_1", '.' → '_' (identifiers here are ASCII).
    private fun mangle(name: String) = name.replace("_", "_1").replace('.', '_')

    private companion object {
        val DECL = Regex(
            """@ExternalSymbolName\("(\w+)"\)\s*(?:private\s+|internal\s+)?external\s+fun\s+(\w+)\s*\(([^)]*)\)(?:\s*:\s*(\w+))?""",
        )
    }
}
