package dev.filament.kmp

/**
 * <code>IndirectLight</code> is used to simulate environment lighting, a form of global illumination.
 *
 * <p>Environment lighting has a two components:</p>
 * <ol>
 *  <li>irradiance</li>
 *  <li>reflections (specular component)</li>
 * </ol>
 *
 * <p>Environments are usually captured as high-resolution HDR equirectangular images and processed
 * by the <b>cmgen</b> tool to generate the data needed by {@link IndirectLight}.</p>
 *
 * <p>Currently {@link IndirectLight} is intended to be used for "distant probes", that is, to represent
 * global illumination from a distant (i.e. at infinity) environment, such as the sky or distant
 * mountains. Only a single {@link IndirectLight} can be used in a {@link Scene}.
 * This limitation will be lifted in the future.</p>
 *
 *
 * <h1>Creation and destruction</h1>
 *
 * <p>An {@link IndirectLight} object is created using the {@link IndirectLight.Builder} and
 * destroyed by calling {@link Engine#destroyIndirectLight}.</p>
 *
 * <pre>
 *  Engine engine = Engine.create();
 *
 *  Scene scene = engine.createScene();
 *
 *  IndirectLight environment = new IndirectLight.Builder()
 *              .reflections(cubemap)
 *              .irradiance(numBands, sphericalHarmonicsCoefficients)
 *              .build(engine);
 *
 *  scene.setIndirectLight(environment);
 * </pre>
 *
 *
 * <h1>Irradiance</h1>
 *
 * <p>The irradiance represents the light that comes from the environment and shines an
 * object's surface.
 * The irradiance is calculated automatically from the Reflections (see below), and generally
 * doesn't need to be provided explicitly.  However, it can be provided separately from the
 * Reflections as
 * <a href="https://en.wikipedia.org/wiki/Spherical_harmonics">Spherical Harmonics</a> (SH) of 1, 2 or
 * 3 bands, respectively 1, 4 or 9 coefficients.</p>
 *
 * <p>Use the <b>cmgen</b> tool to generate the Spherical Harmonics for a given environment.</p>
 *
 *
 * <h1>Reflections</h1>
 *
 * <p>The reflections on object surfaces (specular component) is calculated from a specially
 * filtered cubemap pyramid generated by the <b>cmgen</b> tool.</p>
 *
 * @see Scene
 * @see LightManager
 * @see Texture
 * @see Skybox
 */
expect class IndirectLight {
    /**
     * Use <code>Builder</code> to construct an <code>IndirectLight</code> object instance.
     */
    class Builder {
        /**
         * Set the reflections cubemap mipmap chain.
         *
         * @param cubemap   A mip-mapped cubemap generated by <b>cmgen</b>. Each cubemap level
         *                  encodes the irradiance for a roughness level.
         *
         * @return This Builder, for chaining calls.
         */
        fun reflections(cubemap: Texture): Builder

        /**
         * Sets the irradiance as Spherical Harmonics.
         *
         * <p>Only 1, 2 or 3 bands are allowed.</p>
         *
         * @param bands     Number of spherical harmonics bands. Must be 1, 2 or 3.
         * @param sh        Array containing the spherical harmonics coefficients.
         *                  The size of the array must be <code>3 &times bands<sup>2</sup></code>
         *                  (i.e. 1, 4 or 9 <code>float3</code> coefficients respectively).
         *
         * @return This Builder, for chaining calls.
         */
        fun irradiance(bands: Int, sh: FloatArray): Builder

        /**
         * Sets the irradiance from the radiance expressed as Spherical Harmonics.
         *
         * @param bands     Number of spherical harmonics bands. Must be 1, 2 or 3.
         * @param sh        Array containing the spherical harmonics coefficients.
         *                  The size of the array must be 3 &times <code>bands<sup>2</sup></code>
         *                  (i.e. 1, 4 or 9 <code>float3</code> coefficients respectively).
         *
         * @return This Builder, for chaining calls.
         */
        fun radiance(bands: Int, sh: FloatArray): Builder

        /**
         * Sets the irradiance as a cubemap.
         *
         * @param cubemap   Cubemap representing the Irradiance pre-convolved by
         *                  <code>&lt n &sdot l &gt</code>.
         *
         * @return This Builder, for chaining calls.
         */
        fun irradiance(cubemap: Texture): Builder

        /**
         * Environment intensity (optional).
         *
         * <p>Because the environment is encoded usually relative to some reference, the
         * range can be adjusted with this method.</p>
         *
         * @param envIntensity  Scale factor applied to the environment and irradiance such that
         *                      the result is in <i>lux</i>, or <i>lumen/m^2</i> (default = 30000)
         *
         * @return This Builder, for chaining calls.
         */
        fun intensity(envIntensity: Float): Builder

        /**
         * Specifies the rigid-body transformation to apply to the IBL.
         *
         * @param rotation 3x3 rotation matrix. Must be a rigid-body transform.
         *
         * @return This Builder, for chaining calls.
         */
        fun rotation(rotation: FloatArray): Builder

        /**
         * Creates the IndirectLight object and returns a pointer to it.
         *
         * @param engine The {@link Engine} to associate this <code>IndirectLight</code> with.
         *
         * @return A newly created <code>IndirectLight</code>
         *
         * @exception IllegalStateException if a parameter to a builder function was invalid.
         */
        fun build(engine: Engine): IndirectLight
    }

    /**
     * Sets the environment's intensity.
     *
     * <p>Because the environment is encoded usually relative to some reference, the
     * range can be adjusted with this method.</p>
     *
     * @param intensity  Scale factor applied to the environment and irradiance such that
     *                   the result is in <i>lux</i>, or <i>lumen/m^2</i> (default = 30000)
     */
    fun setIntensity(intensity: Float)

    /**
     * Returns the environment's intensity in lux, or lumen/m^2.
     */
    fun getIntensity(): Float

    /**
     * Sets the rigid-body transformation to apply to the IBL.
     *
     * @param rotation 3x3 rotation matrix. Must be a rigid-body transform.
     */
    fun setRotation(rotation: FloatArray)

    /**
     * Returns the rigid-body transformation applied to the IBL.
     *
     * @param rotation an array of 9 floats to receive the rigid-body transformation applied to
     *                 the IBL or <code>null</code>
     * @return the <code>rotation</code> paramter if it was provided, or a newly allocated float
     * array containing the rigid-body transformation applied to the IBL
     */
    fun getRotation(rotation: FloatArray? = null): FloatArray

    /** @deprecated */
    @Deprecated("Use IndirectLight.getDirectionEstimate(sh, direction)")
    fun getDirectionEstimate(direction: FloatArray? = null): FloatArray

    /** @deprecated */
    @Deprecated("Use IndirectLight.getColorEstimate(colorIntensity, sh, x, y, z)")
    fun getColorEstimate(colorIntensity: FloatArray? = null, x: Float, y: Float, z: Float): FloatArray

    fun getReflectionsTexture(): Texture?

    fun getIrradianceTexture(): Texture?

    fun getNativeObject(): Long

    internal fun invalidate()

    companion object {
        /**
         * Helper to estimate the direction of the dominant light in the environment.
         *
         * <p>This assumes that there is only a single dominant light (such as the sun in outdoors
         * environments), if it's not the case the direction returned will be an average of the
         * various lights based on their intensity.</p>
         *
         * @param sh        pre-scaled 3-bands spherical harmonics
         * @param direction an array of 3 floats to receive a unit vector representing the direction of
         *                 the dominant light or <code>null</code>
         * @return the <code>direction</code> paramter if it was provided, or a newly allocated float
         * array containing a unit vector representing the direction of the dominant light
         *
         * @see LightManager.Builder#direction
         * @see #getColorEstimate
         */
        fun getDirectionEstimate(sh: FloatArray, direction: FloatArray? = null): FloatArray

        /**
         * Helper to estimate the color and relative intensity of the environment in a given direction.
         *
         * @param colorIntensity an array of 4 floats to receive the result or <code>null</code>
         * @param sh        pre-scaled 3-bands spherical harmonics
         * @param x the x coordinate of a unit vector representing the direction of the light
         * @param y the x coordinate of a unit vector representing the direction of the light
         * @param z the x coordinate of a unit vector representing the direction of the light
         *
         * @return A vector of 4 floats where the first 3 components represent the linear color and
         *         the 4th component represents the intensity of the dominant light
         *
         * @see LightManager.Builder#color
         * @see LightManager.Builder#intensity
         * @see #getDirectionEstimate
         * @see #getIntensity
         * @see #setIntensity
         */
        fun getColorEstimate(colorIntensity: FloatArray? = null, sh: FloatArray, x: Float, y: Float, z: Float): FloatArray
    }
}

