package buildlogic.apigen.gaps

import buildlogic.apigen.ApiHeaders
import buildlogic.apigen.c.cApiWriter
import buildlogic.apigen.kotlin.kotlinExternals
import buildlogic.apigen.kotlin.packageDir
import buildlogic.apigen.relativeHeaders
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.UntrackedTask
import org.gradle.process.ExecOperations
import java.io.File
import javax.inject.Inject

/**
 * Writes [report]: each C function the C++ API calls for: bound, and a public Kotlin wrapper calls it (`wrapped`) or none
 * does yet (`unwrapped`); or why it isn't bound (`todo`, `skipped`). Then each enum value and class constant of that API,
 * which no function carries: the Kotlin API declares it (`declared`) or doesn't (`undeclared`; `untyped` when it has no
 * declaration of the enum's name). Committed, so a Filament bump's diff shows what changed and how far it got. Warns when
 * the committed C API or Kotlin externals aren't what the generators would write.
 */
@UntrackedTask(because = "A report to diff, cheap next to reading the AST")
abstract class ApiCoverageTask @Inject constructor(private val exec: ExecOperations) : DefaultTask() {
    @get:Internal abstract val publicHeaders: ConfigurableFileCollection
    @get:Internal abstract val includeDir: DirectoryProperty
    @get:Internal abstract val apiHeadersFile: RegularFileProperty
    @get:Internal abstract val cDir: DirectoryProperty
    @get:Internal abstract val kotlinDir: DirectoryProperty

    /** C module → the Kotlin package of its externals. */
    @get:Internal abstract val packages: MapProperty<String, String>

    @get:Internal abstract val report: RegularFileProperty

    @TaskAction
    fun run() {
        val include = includeDir.get().asFile
        val c = cDir.get().asFile
        val kotlin = kotlinDir.get().asFile
        val apiHeaders = ApiHeaders.parse(apiHeadersFile.get().asFile.readText())
        val writer = cApiWriter(exec, temporaryDir, include, relativeHeaders(publicHeaders.files, include), apiHeaders, c)
        val cFiles = writer.write()
        warnStale("C API", "generateCApi", c, cFiles, apiHeaders.modules.keys.map { "$it/generated" })
        warnStale("Kotlin externals", "generateKotlinExternals", kotlin, kotlinExternals(c, packages.get()), packages.get().map { (m, p) -> packageDir(m, p) })

        // The wrappers: main sources outside capi, comments aside (tests call externals directly).
        val sources = kotlin.walkTopDown().filter { f -> f.extension == "kt" && f.invariantSeparatorsPath.let { MAIN.containsMatchIn(it) && "/capi/" !in it } }
            .sortedBy { it.path }.joinToString("\n") { COMMENT.replace(it.readText(), "") }
        val called = FILA.findAll(sources).mapTo(HashSet()) { it.value }
        val lines = writer.bindings.distinctBy { it.c to it.cpp }.sortedWith(compareBy({ it.c }, { it.cpp })).map { b ->
            val status = b.gap?.substringBefore(':') ?: if (b.c in called) "wrapped" else "unwrapped"
            "${status.padEnd(9)} ${b.c} = ${b.cpp}" + (b.gap?.substringAfter(": ")?.let { "  -- $it" } ?: "")
        }
        val counts = lines.groupingBy { it.substringBefore(' ') }.eachCount()
        val summary = STATUSES.joinToString(", ") { "${counts[it] ?: 0} $it" }
        val values = writer.enums.flatMap { e ->
            // Kotlin names an enum as the API's alias does: Texture.InternalFormat for backend::TextureFormat.
            val scope = writer.aliasesOf(e.name).mapNotNull { kotlinScope(sources, it) }.ifEmpty { return@flatMap listOf("untyped    ${e.name}") }.joinToString("\n")
            e.constants.map { (name, _) -> declared(scope, name) + " ${e.name}::$name" }
        } + writer.constants.map { c -> declared(kotlinScope(sources, c.substringBeforeLast("::")).orEmpty(), c.substringAfterLast("::")) + " $c" }
        val valueCounts = values.groupingBy { it.substringBefore(' ') }.eachCount()
        val valueSummary = VALUE_STATUSES.joinToString(", ") { "${valueCounts[it] ?: 0} $it" }
        report.get().asFile.writeText(
            "# Generated by apiCoverage; do not edit. Each C function the C++ API calls for: bound, and a public Kotlin wrapper\n" +
                "# calls it (wrapped) or none does yet (unwrapped); or why it isn't bound (todo, skipped).\n# $summary\n\n" + lines.joinToString("\n", postfix = "\n") +
                "\n# Each enum value and class constant of that API: the Kotlin API declares it (declared) or doesn't (undeclared);\n" +
                "# untyped: Kotlin has no declaration of the enum's name.\n# $valueSummary\n\n" + values.joinToString("\n", postfix = "\n"),
        )
        logger.lifecycle("API coverage: $summary; $valueSummary")
        logger.lifecycle("Report: ${report.get().asFile.toURI()} (git diff it to see what changed)")
    }

    private fun declared(scope: String, name: String) = if (Regex("""\b$name\b""").containsMatchIn(scope)) "declared  " else "undeclared"

    /**
     * The bodies of the Kotlin declarations the C++ [qualified] name maps to: each segment's declarations inside the
     * previous one's (namespaces have none), or anywhere when the owner doesn't nest it. Null when Kotlin declares none.
     */
    private fun kotlinScope(sources: String, qualified: String): String? {
        val segments = qualified.split("::")
        var scope = sources
        segments.forEachIndexed { i, segment ->
            val nested = bodies(scope, segment)
            scope = when {
                nested.isNotEmpty() -> nested
                i < segments.lastIndex -> scope
                else -> bodies(sources, segment).ifEmpty { return null }
            }
        }
        return scope
    }

    /** The brace-matched bodies of every declaration of [name] in [text]. */
    private fun bodies(text: String, name: String) = Regex("""\b(?:class|object|interface)\s+$name\b""").findAll(text).joinToString("\n") { m ->
        // The body's brace follows the header: constructor parameters aside, no other declaration starts before it.
        val header = StringBuilder()
        var parens = 0
        var open = m.range.last + 1
        while (open < text.length && (parens > 0 || text[open] != '{')) {
            when (text[open]) {
                '(' -> parens++
                ')' -> parens--
                else -> if (parens == 0) header.append(text[open])
            }
            open++
        }
        if (open == text.length || '}' in header || NEXT_DECLARATION.containsMatchIn(header)) return@joinToString ""
        var depth = 0
        for (i in open until text.length) when (text[i]) {
            '{' -> depth++
            '}' -> if (--depth == 0) return@joinToString text.substring(open, i + 1)
        }
        ""
    }

    /** Warns about [expected] files (by path under [root]) that differ from [root], and files under [dirs] it doesn't list. */
    private fun warnStale(what: String, task: String, root: File, expected: Map<String, String>, dirs: List<String>) {
        val onDisk = dirs.flatMap { d -> root.resolve(d).walkTopDown().filter { it.isFile }.map { it.relativeTo(root).invariantSeparatorsPath } }
        val stale = expected.filter { (path, text) -> root.resolve(path).let { !it.isFile || it.readText() != text } }.keys + (onDisk - expected.keys)
        if (stale.isNotEmpty()) logger.warn("The committed $what is stale (${stale.size} files, e.g. ${stale.first()}): run $task")
    }

    private companion object {
        val FILA = Regex("""\bFila\w+""")
        val MAIN = Regex("""/src/\w*Main/""")
        val COMMENT = Regex("""//[^\n]*|/\*[\s\S]*?\*/""")
        val STATUSES = listOf("wrapped", "unwrapped", "todo", "skipped")
        val VALUE_STATUSES = listOf("declared", "undeclared", "untyped")
        val NEXT_DECLARATION = Regex("""\b(?:class|object|interface|fun|val|var|typealias)\b""")
    }
}
