package buildlogic.apigen.gaps

import buildlogic.apigen.ApiGenTask
import buildlogic.apigen.kotlin.kotlinExternals
import buildlogic.apigen.kotlin.packageDir
import buildlogic.apigen.stale
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.UntrackedTask
import java.io.File

/**
 * Writes `api-coverage.txt`: each C function the C++ API calls for: bound, and a public Kotlin wrapper calls it
 * (`wrapped`) or none does yet (`unwrapped`); or why it isn't bound (`todo`, `skipped`). Then each enum value and class
 * constant of that API, which no function carries: the Kotlin API declares it (`declared`) or doesn't (`undeclared`;
 * `untyped` when it has no declaration of the enum's name). Committed, so a library bump's diff shows what changed and
 * how far it got. Warns when the committed C API or Kotlin externals aren't what the generators would write.
 */
@UntrackedTask(because = "A report to diff, cheap next to reading the AST")
abstract class ApiCoverageTask : ApiGenTask() {
    @get:Internal abstract val kotlinDir: DirectoryProperty

    /** C module → the Kotlin package of its externals. */
    @get:Internal abstract val packages: MapProperty<String, String>

    @TaskAction
    fun run() {
        val apiGen = apiGen()
        val c = apiGen.cDir
        val kotlin = kotlinDir.get().asFile
        val headers = apiGen.headers
        val writer = apiGen.writer()
        warnStale("C API", "generateCApi", apiGen.stale(writer.write()))
        warnStale("Kotlin externals", "generateKotlinExternals",
            stale(kotlin, kotlinExternals(c, packages.get()), packages.get().map { (m, p) -> kotlin.resolve(packageDir(m, p)) }))

        // The wrappers: main sources outside capi, comments aside (tests call externals directly).
        val sources = kotlin.walkTopDown().filter { f -> f.extension == "kt" && f.invariantSeparatorsPath.let { MAIN.containsMatchIn(it) && "/capi/" !in it } }
            .sortedBy { it.path }.joinToString("\n") { COMMENT.replace(it.readText(), "") }
        val called = Regex("""\b${Regex.escape(config.get().prefix)}\w+""").findAll(sources).mapTo(HashSet()) { it.value }
        val lines = writer.bindings.distinctBy { it.c to it.cpp }.sortedWith(compareBy({ it.c }, { it.cpp })).map { b ->
            val status = b.gap?.substringBefore(':') ?: if (b.c in called) "wrapped" else "unwrapped"
            "${status.padEnd(9)} ${b.c} = ${b.cpp}" + (b.gap?.substringAfter(": ")?.let { "  -- $it" } ?: "")
        }
        val summary = summary(lines, STATUSES)
        val api = writer.api
        val declarations = KotlinDeclarations(sources)
        val values = (api.apiEnums(headers).flatMap { e ->
            // Kotlin names an enum as the API's alias does: Texture.InternalFormat for backend::TextureFormat.
            val scope = declarations.scope(api.aliasesOf(e.name)) ?: return@flatMap listOf("untyped" to e.name)
            e.constants.map { "${e.name}::${it.first}" }.filter { api.skipReason(it) == null }.map { declarations.status(scope, it) to it }
        } + api.apiConstants(headers).map { c ->
            (declarations.scope(listOf(c.substringBeforeLast("::")))?.let { declarations.status(it, c) } ?: "untyped") to c
        }).map { (status, name) -> "${status.padEnd(10)} $name" }
        val valueSummary = summary(values, VALUE_STATUSES)
        val report = c.resolve("api-coverage.txt")
        report.writeText(
            "# Generated by apiCoverage; do not edit. Each C function the C++ API calls for: bound, and a public Kotlin wrapper\n" +
                "# calls it (wrapped) or none does yet (unwrapped); or why it isn't bound (todo, skipped).\n# $summary\n\n" + lines.joinToString("\n", postfix = "\n") +
                "\n# Each enum value and class constant of that API: the Kotlin API declares it (declared) or doesn't (undeclared);\n" +
                "# untyped: Kotlin has no declaration of the enum's, or the constant's owner's, name.\n# $valueSummary\n\n" + values.joinToString("\n", postfix = "\n"),
        )
        logger.lifecycle("API coverage: $summary; $valueSummary")
        logger.lifecycle("Report: ${report.toURI()} (git diff it to see what changed)")
    }

    private fun summary(lines: List<String>, statuses: List<String>) =
        lines.groupingBy { it.substringBefore(' ') }.eachCount().let { counts -> statuses.joinToString(", ") { "${counts[it] ?: 0} $it" } }

    private fun warnStale(what: String, task: String, stale: Set<String>) {
        if (stale.isNotEmpty()) logger.warn("The committed $what is stale (${stale.size} files, e.g. ${stale.first()}): run $task")
    }

    private companion object {
        val MAIN = Regex("""/src/\w*Main/""")
        val COMMENT = Regex("""//[^\n]*|/\*[\s\S]*?\*/""")
        val STATUSES = listOf("wrapped", "unwrapped", "todo", "skipped")
        val VALUE_STATUSES = listOf("declared", "undeclared", "untyped")
    }
}
