import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import java.util.Base64 as JavaBase64

plugins {
    id("filament-kmp-module")
}

filamentModule {
    xcframeworkName.set("Gltfio")
}

val filaVersion = project.property("filaVersion") as String
val libVersion = project.property("libVersion") as String

// Additional prebuilts needed by gltfio-c beyond what :kotlin:filament already embeds.
// (filament, backend, utils, filaflat, filabridge, zstd are covered by the filament module.)
val GLTFIO_PREBUILT_LIBS = listOf(
    "libgltfio_core.a",
    "libdracodec.a",
    "libbasis_transcoder.a",  // transitive dep of gltfio_core
    "libmikktspace.a",        // transitive dep of gltfio_core
    "libstb.a",
    "libimage.a",
    "libimageio-lite.a",
    "libktxreader.a",
    "libuberarchive.a",       // ubershader package (UBERARCHIVE_PACKAGE, uberz::*)
    "libuberzlib.a",          // ubershader archive helpers (transitive of uberarchive)
)

kotlin {
    sourceSets {
        commonMain.dependencies {
            implementation(project(":kotlin:filament"))
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(project(":kotlin:test-support"))
        }
        androidMain.dependencies {
            implementation("com.google.android.filament:gltfio-android:$filaVersion")
        }
        jvmMain.dependencies {
            // Project Panama (FFM): the combined libfilament-c image + jextract-generated
            // FilamentC already cover the gltfio surface. Replaces the JNI :java:gltfio dep.
            api(project(":java"))
        }
        webMain.dependencies {
            implementation(project(":web"))
        }
    }

    // ── Embed test .glb assets as base64 into a generated commonTest source ──────
    // Resource access differs per platform (JVM classpath / iOS bundle / browser
    // HTTP / Android assets), so instead of per-platform IO we encode the committed
    // .glb files into a generated Kotlin object decoded at runtime. This makes the
    // real asset bytes available identically on every target. .glb files in
    // src/commonTest/glb are the source of truth.
    val glbInputDir = layout.projectDirectory.dir("src/commonTest/glb")
    val glbGenDir = layout.buildDirectory.dir("generated/embeddedGlb/kotlin")
    val generateEmbeddedGlb = tasks.register("generateEmbeddedGlb") {
        val inDir = glbInputDir.asFile
        val outRoot = glbGenDir.get().asFile
        inputs.dir(glbInputDir).withPropertyName("glb")
            .withPathSensitivity(PathSensitivity.RELATIVE)
        outputs.dir(glbGenDir).withPropertyName("out")
        doLast {
            val files = (inDir.listFiles { f -> f.isFile && f.name.endsWith(".glb") }
                ?: emptyArray()).sortedBy { it.name }
            val pkgDir = outRoot.resolve("io/github/erkko68/filament/gltfio/testutils")
            pkgDir.mkdirs()
            val sb = StringBuilder()
            sb.appendLine("package io.github.erkko68.filament.gltfio.testutils")
            sb.appendLine()
            sb.appendLine("import kotlin.io.encoding.Base64")
            sb.appendLine("import kotlin.io.encoding.ExperimentalEncodingApi")
            sb.appendLine()
            sb.appendLine("// Generated by :kotlin:gltfio:generateEmbeddedGlb from src/commonTest/glb. Do not edit.")
            sb.appendLine("@OptIn(ExperimentalEncodingApi::class)")
            sb.appendLine("internal object EmbeddedGlb {")
            // JVM caps a single string constant at 64 KB of UTF-8; base64 is ASCII so
            // chunk well under that and concatenate before decoding.
            sb.appendLine("    private fun d(vararg c: String): ByteArray = Base64.decode(c.joinToString(\"\"))")
            for (f in files) {
                val ident = f.nameWithoutExtension.replace(Regex("[^A-Za-z0-9]"), "_")
                val b64 = JavaBase64.getEncoder().encodeToString(f.readBytes())
                val chunks = b64.chunked(32000)
                sb.appendLine("    val $ident: ByteArray by lazy {")
                sb.appendLine("        d(")
                chunks.forEachIndexed { i, c ->
                    sb.appendLine("            \"$c\"" + if (i < chunks.lastIndex) "," else "")
                }
                sb.appendLine("        )")
                sb.appendLine("    }")
            }
            sb.appendLine("}")
            pkgDir.resolve("EmbeddedGlb.kt").writeText(sb.toString())
        }
    }
    sourceSets.named("commonTest") {
        kotlin.srcDir(generateEmbeddedGlb)
    }

    targets.withType<KotlinNativeTarget>().configureEach {
        compilations.getByName("main").cinterops {
            create("gltfio") {
                defFile(project.file("src/nativeInterop/cinterop/gltfio.def"))
                includeDirs(
                    project.file("../../c/gltfio/c"),
                    project.file("../../c/filament/c"),
                    project.file("../../include"),
                )
            }
        }
        applyFilamentNative(project, "gltfio", "gltfio-c", GLTFIO_PREBUILT_LIBS)
    }
}
