package io.github.erkko68.filament.web

// unhandled import: * as glm from "gl-matrix"

// The remainder of this file is generated by beamsplitter
/**
 * Generic quality level.
 */
@JsName("View\$QualityLevel")
external class View_QualityLevel : JsAny {
companion object {
val LOW: View_QualityLevel
val MEDIUM: View_QualityLevel
val HIGH: View_QualityLevel
val ULTRA: View_QualityLevel
}
}
