// Generated by generateCApi; do not edit. The helpers the generated forwarders call: nothing here knows the library.
// What only the library can write goes in a hand-written header that includes this one (the config's bridgeHeader).
#pragma once

#include <array>
#include <bit>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iterator>
#include <memory>
#include <optional>
#include <utility>
#include <vector>

namespace apigen {

// Called by a function whose C++ the target's headers leave out (#if guards around the declaration).
[[noreturn]] inline void unavailable(const char* name) {
    std::fprintf(stderr, "%s is unavailable on this platform\n", name);
    std::abort();
}

// C and C++ types naming one object (a handle, a math mirror): cpp() and c() convert pointers between them.
#define APIGEN_TYPE(C, ...) \
    inline __VA_ARGS__* cpp(C* p) { return reinterpret_cast<__VA_ARGS__*>(p); } \
    inline const __VA_ARGS__* cpp(const C* p) { return reinterpret_cast<const __VA_ARGS__*>(p); } \
    inline C* c(__VA_ARGS__* p) { return reinterpret_cast<C*>(p); } \
    inline const C* c(const __VA_ARGS__* p) { return reinterpret_cast<const C*>(p); }

// Hook: specialize for a math type that needs fixing up once it's copied from C's mirror (a lane C leaves unset).
template<typename T>
struct Mirrored {
    static void fix(T&) {}
};

// Hook: specialize for a container that takes only so many elements.
template<typename C>
constexpr uint32_t capacity = UINT32_MAX;

// C's mirror as the math type T: the same bytes, wherever C put them.
template<typename T, typename C>
T math(const C& c) {
    static_assert(sizeof(T) == sizeof(C));
    T t;
    std::memcpy(static_cast<void*>(&t), &c, sizeof(T));
    Mirrored<T>::fix(t);
    return t;
}

// A math type as C's mirror C.
template<typename C, typename T>
C mirror(const T& t) {
    static_assert(sizeof(T) == sizeof(C));
    C c;
    std::memcpy(&c, static_cast<const void*>(&t), sizeof(C));
    return c;
}

// C's mirror as the T& the callee reads and writes: an aligned copy, written back when the call ends.
template<typename T, typename C>
struct InOut {
    C* c;
    T value;

    explicit InOut(C* c) : c(c), value(math<T>(*c)) {}
    ~InOut() { *c = mirror<C>(value); }
    operator T&() { return value; }
};

// C's array as the container the callee takes: anything with push_back, a std::array, or a view (made from a pointer
// and a size, like std::span), whose elements live as long as the Items, until the end of the call. element(i) makes
// each item. Only for a T the elements make, so overloads taking different arrays stay apart.
template<typename T, typename F>
concept Makes = requires(F element) { T(element(0u)); };

template<typename C>
concept Growable = requires(C c) { c.push_back(std::declval<typename C::value_type>()); };

template<typename F>
struct Items {
    uint32_t count;
    F element;
    mutable std::shared_ptr<void> storage;

    template<typename C> requires Growable<C> && Makes<typename C::value_type, F>
    operator C() const {
        C v;
        if constexpr (requires { v.reserve(count); }) v.reserve(count);
        for (uint32_t i = 0; i < count && i < capacity<C>; i++) v.push_back(typename C::value_type(element(i)));
        return v;
    }

    template<typename T, size_t N> requires Makes<T, F>
    operator std::array<T, N>() const {
        std::array<T, N> a{};
        for (uint32_t i = 0; i < count && i < N; i++) a[i] = T(element(i));
        return a;
    }

    template<typename V> requires (!Growable<V>) && Makes<typename V::value_type, F> &&
        requires(std::vector<typename V::value_type>& v) { V(v.data(), v.size()); }
    operator V() const {
        auto v = std::make_shared<std::vector<typename V::value_type>>();
        v->reserve(count);
        for (uint32_t i = 0; i < count; i++) v->push_back(typename V::value_type(element(i)));
        storage = v;
        return V(v->data(), v->size());
    }
};

template<typename F>
Items<F> items(uint32_t count, F element) { return { count, element }; }

// C's array as the std::array<T, N> the callee takes by pointer or reference: element(i) makes each T, and
// store(t, i) writes the callee's changes back into C's array when the call ends.
template<typename F, typename S>
struct Updated {
    uint32_t count;
    F element;
    S store;
    std::shared_ptr<void> storage;
    void (*writeBack)(Updated&) = nullptr;

    template<typename T, size_t N>
    std::array<T, N>* array() {
        auto a = std::make_shared<std::array<T, N>>();
        for (uint32_t i = 0; i < count && i < N; i++) (*a)[i] = T(element(i));
        storage = a;
        writeBack = [](Updated& u) {
            auto& a = *static_cast<std::array<T, N>*>(u.storage.get());
            for (uint32_t i = 0; i < u.count && i < N; i++) u.store(a[i], i);
        };
        return a.get();
    }

    template<typename T, size_t N>
    operator std::array<T, N>*() { return array<T, N>(); }

    template<typename T, size_t N>
    operator std::array<T, N>&() { return *array<T, N>(); }

    ~Updated() { if (writeBack) writeBack(*this); }
};

template<typename F, typename S>
Updated<F, S> updated(uint32_t count, F element, S store) { return { count, element, store }; }

// Fills an array field from C's array, up to either's size.
template<typename T, size_t N, typename F>
void assign(T (&array)[N], const Items<F>& items) {
    for (uint32_t i = 0; i < items.count && i < N; i++) array[i] = T(items.element(i));
}

// Stores up to capacity of items into C's array; returns how many there are.
template<typename V, typename F>
uint32_t copy(const V& items, uint32_t capacity, F store) {
    for (uint32_t i = 0; i < capacity && i < std::size(items); i++) store(items[i], i);
    return uint32_t(std::size(items));
}

// C's nullable pointer as the std::optional the callee takes; convert(*p) makes its value.
template<typename T, typename F>
auto optional(const T* p, F convert) -> std::optional<decltype(convert(*p))> {
    if (!p) return std::nullopt;
    return convert(*p);
}

// Stores an optional's value, if it has one; returns whether it did.
template<typename T, typename F>
bool present(const std::optional<T>& o, F store) {
    if (o) store(*o);
    return o.has_value();
}

} // namespace apigen
