plugins {
    kotlin("multiplatform")
    id("filament-publish")
}

version = findProperty("libVersion") as? String ?: "0.1.0-SNAPSHOT"

// ──────────────────────────────────────────────────────────────────────────────
// Kotlin external declarations for Filament.js
//
// The externals under src/webMain are committed, hand-maintained sources. They
// were originally generated by Karakum from upstream `filament.d.ts` plus a
// curated overlay, but the d.ts lags the real embind surface registered in
// upstream `web/filament-js/jsbindings.cpp` (the source of truth), so they are
// now maintained by hand against jsbindings.cpp directly.
// Run scripts/dev/check-js-bindings.sh on every filaVersion bump to audit the
// declared surface against upstream.
// ──────────────────────────────────────────────────────────────────────────────

kotlin {
    js {
        browser()
    }
    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    // `js` + `wasmJs` + applyDefaultHierarchyTemplate() produces a shared `webMain`.
    // The externals live there so a single set feeds both targets.
    applyDefaultHierarchyTemplate()

    sourceSets {
        webMain {
            dependencies {
                // `api` so consuming modules (kotlin/*/webMain) can resolve the wrapper
                // types that appear in the external signatures (web.html.*, js.array.*,
                // js.core.*, …). kotlin-wrappers publishes these as multiplatform
                // (js + wasmJs) artifacts. Pinned: still-newer wrappers made the
                // TypedArrays generic (Float32Array<B>), which the externals don't
                // parameterise.
                api(project.dependencies.platform("org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:2026.8.5"))
                api("org.jetbrains.kotlin-wrappers:kotlin-js")
                api("org.jetbrains.kotlin-wrappers:kotlin-web")
                api("org.jetbrains.kotlin-wrappers:kotlin-browser")
                // Supplies the stdlib-shaped org.w3c.dom / org.khronos.webgl / kotlinx.browser
                // packages for BOTH js and wasmJs, so the DOM / typed-array externals (and the
                // actuals that use them) resolve on wasmJs.
                api("org.jetbrains.kotlinx:kotlinx-browser:0.5.0")
            }
        }
        jsMain {
            dependencies {
                implementation(kotlin("stdlib-js"))
            }
        }
    }
}
